### ISSUE TITLE
Long non-nullable HISTORY and COMMENT cards break headers

### ISSUE THREAD

**Issue by attipaci** [nom-tam-fits/nom-tam-fits#102]
Non-nullable HISTORY and COMMENT cards (really any 'comment-like' cards) whose footprint exceeds the 80-character line limit, are added to the header as is, producing longer than 80-character lines, and thus breaching the header format requirement. (The resulting headers become unreadable for most, if not all, FITS tools!)

The expected behavior is:
 
  * Long comment-style cards (e.g. HISTORY, COMMENT) should either throw an appropriate Exception upon creation (for non-nullable cards), or else get truncated at the 80-character limit (for nullable cards), when the long keyword convention is not enabled/used.

  * When the long keyword convention is enabled, long non-nullable comment-style entries (e.g. HISTORY, COMMENT) should be wrapped using CONTINUE keys, just like regular keywords. (A fix to that end will also need to make sure that CONTINUE keys are properly parsed for comment-style cards when reading a header!)

At the root of the issue is that only long card 'values' are wrapped using the OGIP 1.0 convention, but that HISTORY and COMMENT entries have no 'value' (null), but only a 'comment' field. The quick patch (for writing) may be to treat the (non-nullable) comment fields in comment-like cards just the same as values (but not for regular keys!!!).

Perhaps, the better long-term fix would be that comment-style keys carry their content as 'value' rather than the optional (and always truncatable) 'comment', and are distinguished from regular keywords via a boolean flag (e.g. HeaderCard.value=null --> HeaderCard.isComment=true). This could make formatting a little more regular...

A workaround (until the issue is fixed) is that the user must take care not to create HISTORY or COMMENT cards with content longer than 72 characters.

-- Attila.

**Comment by ritchieGitHub** [comment]
Strange what I remember the lengths are cut to fit the specification, will look into this tomorrow. Do you have a failing unit test for me? (speeds up the work). If confirmed, this bug is important enough to create a release right away.

**Comment by attipaci** [comment]
Hi Ritchie,


Here is something... Not quite a unit test, but close enough... This is 
the test code I used myself, and the simple FITS output it produces.

I hope this helps...

I'm a little snowed in with work until late September, at least, so I 
cannot offer much help -- not it the short term, at least... But, if it 
turns out to be hairy to fix without breaking other things, I can 
probably help out a bit starting in October...

If you or someone else can fix it before, all the better!!!

Thanks,

-- A.

**Comment by ritchieGitHub** [comment]
should not be a problem, will fix this tomorrow. (your attached test code got lost somewhere...)
