### ISSUE TITLE
solar data image has decompressing problems

### ISSUE THREAD

**Issue by ritchieGitHub** [nom-tam-fits/nom-tam-fits#105]
This is a solar data image and the pixel values in the disk should be in the range ~+/- 50000.  However it looks like all of the values that were not Int.MIN_VALUE were offset by Int.MIN_VALUE from their correct value so the values cluster around Int.MIN/MAX_VALUE. It was easy to recover the correct values as a workaround but very confusing to the user.

Also when in the header  of the HDU that CompressedImageHDU.asImageHDU() returns some of the keywords relating to the compressed table have not been deleted, notably TFIELDS and TTYPE1.

**Comment by ritchieGitHub** [comment]
this was a problem of integer overflow in case of negative values in combination with a defined blank value of Integer.MIN_VANUE. then an unsigned integer overflow was not handled correctly in the rice decompression algorithm.

**Comment by ritchieGitHub** [comment]
@TomMcGlynn could you test if my fix works for your contact?

**Comment by ritchieGitHub** [comment]
@TomMcGlynn any response yet?

**Comment by ritchieGitHub** [comment]
@TomMcGlynn any response yet, or shall we assume that the problem is fixed?

**Comment by TomMcGlynn** [comment]
I never got anything further, so I guess things are working...


Richard van Nieuwenhoven wrote:
