### ISSUE TITLE
Remove redundant spaces in HIERARCH keys

### ISSUE THREAD

**Issue by JonCook** [nom-tam-fits/nom-tam-fits#106]
Hi,

With the latest version of FITS we end up with for example:
HIERARCH  key.META_2= 'Horizontal'

Do you know if there is any quick way or trick to remove the space after the = sign, I know it seems very trivial but we these FITS files we generate with the space can no longer be read by some old software we have and unfortunately we can't change that old software quite so easily as the latest.

Before we had:
HIERARCH  key.META_2='Horizontal'

Perhaps there is a way via IHierarchKeyFormatter.

Many thanks

**Comment by ritchieGitHub** [comment]
Could you try the current snapshot? the new setting is here:
nom.tam.fits.FitsFactory.setSkipBlankAfterAssign(boolean)

**Comment by JonCook** [comment]
Hi,

I tested with the latest snapshot but I'm afraid something doesn't work. Simply switching:
FitsFactory.setSkipBlankAfterAssign(true);

And I lose the value inside the HeaderCard object. For example before switching on I have a header card toString with:
TIMESYS = 'UTC     '           / All dates are in UTC time       

Inside the object the value is UTC and the comment is All dates are in UTC time

When I switch it on:
I have a toString
TIMESYS   ='UTC      '           / All dates are in UTC time                    
The value is null and the comment is:
='UTC      '           / All dates are in UTC time

Something seems to have gone wrong with the translation inside HeaderCard.
Thanks

**Comment by ritchieGitHub** [comment]
Thanks for testing, will try to find the problem this Friday. sorry that this one takes that long..

**Comment by ritchieGitHub** [comment]
I can not reproduce this, this is my test case:
```java
    @Test()
    public void testHeaderCardFormat() throws Exception {
        HeaderCard card = HeaderCard.create("TIMESYS = 'UTC ' / All dates are in UTC time");
        FitsFactory.setSkipBlankAfterAssign(true);
        assertEquals("UTC", card.getValue());
        assertEquals("All dates are in UTC time", card.getComment());
        assertEquals("TIMESYS", card.getKey());
        assertEquals("TIMESYS ='UTC      '           / All dates are in UTC time                      ", card.toString());
    }                     
```
could you change the test so your problem happens?

**Comment by ritchieGitHub** [comment]
sorry, just got it! the correct test must be:
```java
    @Test()
    public void testHeaderCardFormat() throws Exception {
        HeaderCard card = HeaderCard.create("TIMESYS = 'UTC ' / All dates are in UTC time");
        FitsFactory.setSkipBlankAfterAssign(true);
        assertEquals("UTC", card.getValue());
        assertEquals("All dates are in UTC time", card.getComment());
        assertEquals("TIMESYS", card.getKey());
        assertEquals("TIMESYS ='UTC      '           / All dates are in UTC time                      ", card.toString());

        card = HeaderCard.create("TIMESYS ='UTC ' / All dates are in UTC time");
        assertEquals("UTC", card.getValue());
        assertEquals("All dates are in UTC time", card.getComment());
        assertEquals("TIMESYS", card.getKey());
        assertEquals("TIMESYS ='UTC      '           / All dates are in UTC time                      ", card.toString());
    }
```

**Comment by ritchieGitHub** [comment]
Ok, @JonCook lets test again

**Comment by JonCook** [comment]
Hi, I tested it again with nom-tam-fits-1.15.2-20160909.050729-5.jar. I simply updated the library and enabled FitsFactory.setSkipBlankAfterAssign(true);

But I'm afraid the Fits files which get written out by our system our now invalid according to http://fits.gsfc.nasa.gov/fits_verify.html. I don't really understand the errors so well.

Thanks
Jon

**Comment by ritchieGitHub** [comment]
The handling for hierach cards is now special too ;-) I have to look into this, lets see if I can do something tonight.

**Comment by JonCook** [comment]
OK thanks. I never thought a space could be so problematic ;-)

**Comment by ritchieGitHub** [comment]
Strange, it looks correctly to me, can it be that http://fits.gsfc.nasa.gov/fits_verify.html does not allow for the missing blank? Just made a test case with hierarchy cards and they seem OK to me.

**Comment by JonCook** [comment]
I will try. The problem comes reading this FITS back in with version 1.06. Maybe that can be related to issue #103. However I will try and create a better example.

Thanks

**Comment by ritchieGitHub** [comment]
that should not be related, because that issue is mostly repaired.

**Comment by wcleveland** [comment]
I'm trying to catch up with the issue, but I would like to point out that the FITS specification explicitly requires a space after the equals in standard key+value header cards.

**Comment by ritchieGitHub** [comment]
yes, this is a special request feature for very old files ;)
@JonCook maybe you problem is that you want to read without the blank and write with the blank? Then you should reset the setting before writing.

**Comment by ritchieGitHub** [comment]
@JonCook do you have new informations?

**Comment by JonCook** [comment]
Hi, Sorry for the delay. Yes it is working as expected. I only need to switch it on when writing HIERARCH cards. Thanks.

**Comment by ritchieGitHub** [comment]
great!
