### ISSUE TITLE
No tiler for ImageHDU from uncompressing a CompressedImageHDU?

### ISSUE THREAD

**Issue by StephenWampler** [nom-tam-fits/nom-tam-fits#107]
There doesn't seem to be a tiler installed in an ImageHDU that results from calling asImageHDU()
on a CompressedImageHDU  - getTiler() returns null.  Is that intentional?  I'd be happy with a tiler that returns the entire data buffer as ImageData.ImageDataTiler does.

**Comment by StephenWampler** [comment]
Sorry - this with 1.15.1.

**Comment by ritchieGitHub** [comment]
should be no problem, have to check the code. Only I have to wait till Sunday before I have time again. Sorry for the deplay

**Comment by StephenWampler** [comment]
Not a problem - I have enough to keep me busy!

**Comment by ritchieGitHub** [comment]
Yes, this was really missing. Should be fixed now, could you test the snapshot?

**Comment by ritchieGitHub** [comment]
version: 1.15.2-SNAPSHOT

<repository>
        <id>sonatype-snapshots</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>

**Comment by StephenWampler** [comment]
On 09/25/2016 07:56 AM, Richard van Nieuwenhoven wrote:
> version: 1.15.2-SNAPSHOT
>
>
> sonatype-snapshots
> https://oss.sonatype.org/content/repositories/snapshots
>
> true

Thanks - but the latest (only) snapshot I see there for nomtamfits is 1.11.2
from last year.  Does it take a while to show up?

-Steve


-- 
Steve Wampler -- swampler@noao.edu
The gods that smiled on your birth are now laughing out loud.

**Comment by ritchieGitHub** [comment]
https://oss.sonatype.org/content/repositories/snapshots/gov/nasa/gsfc/heasarc/nom-tam-fits/1.15.2-SNAPSHOT/

**Comment by StephenWampler** [comment]
On 09/25/2016 04:21 PM, Richard van Nieuwenhoven wrote:
> https://oss.sonatype.org/content/repositories/snapshots/gov/nasa/gsfc/heasarc/nom-tam-fits/1.15.2-SNAPSHOT/

Thanks - I was looking the wrong place.

However, I don't see any change with that snapshot.  The CompressedImageHDU asImageData() method
still returns an ImageHDU with no tiler.  In looking at the code for ImageData from that snapshot
it looks as though the only way that a tiler is attached is if ImageData's read(ArrayDataInput i)
is called, but since the image data is not being read, but rather uncompressed from the
compressed image data, that method isn't called (nor can it be called!).

(I also see that the 1.15.2 SNAPSHOT date is Sept 9.  Is that correct?)

Not that I know much about this, but a possible fix would be to call data.setTiler(...)
from inside asImageHDU() in CompressedImageHDU.  I think the default ImageDataTiler as
defined in ImageData.java would work, but I don't think it's accessible from CompressedImageHDU.

Any help is appreciated!

-Steve
-- 
Steve Wampler -- swampler@noao.edu
The gods that smiled on your birth are now laughing out loud.

**Comment by StephenWampler** [comment]
On 09/26/2016 08:21 AM, Steve Wampler wrote:
> On 09/25/2016 04:21 PM, Richard van Nieuwenhoven wrote:
>> https://oss.sonatype.org/content/repositories/snapshots/gov/nasa/gsfc/heasarc/nom-tam-fits/1.15.2-SNAPSHOT/
>
> Thanks - I was looking the wrong place.
>
> However, I don't see any change with that snapshot.  The CompressedImageHDU asImageData() method
> still returns an ImageHDU with no tiler.  In looking at the code for ImageData from that snapshot
> it looks as though the only way that a tiler is attached is if ImageData's read(ArrayDataInput i)
> is called, but since the image data is not being read, but rather uncompressed from the
> compressed image data, that method isn't called (nor can it be called!).
>
> (I also see that the 1.15.2 SNAPSHOT date is Sept 9.  Is that correct?)

Nevermind.  I erred.  Ignore that mail..

-- 
Steve Wampler -- swampler@noao.edu
The gods that smiled on your birth are now laughing out loud.

**Comment by StephenWampler** [comment]
On 09/25/2016 04:21 PM, Richard van Nieuwenhoven wrote:
> https://oss.sonatype.org/content/repositories/snapshots/gov/nasa/gsfc/heasarc/nom-tam-fits/1.15.2-SNAPSHOT/

That works just fine - thanks!  (and sorry for the fluff emails along the way...).


-- 
Steve Wampler -- swampler@noao.edu
The gods that smiled on your birth are now laughing out loud.
