### ISSUE TITLE
Can't decompress FITS file using nom.tam.fits

### ISSUE THREAD

**Issue by mabula117** [nom-tam-fits/nom-tam-fits#108]
Dear all,

I can't decompress an image in a FITS file using the nom.tam.fits library.

I have used the following code:

BasicHDU<?>[] fitsFileHDU = null; 
try {
	InputStream fileStream = new BufferedInputStream(new FileInputStream(imageFile));
	Fits fitsFile = new Fits(fileStream);
	fitsFileHDU = fitsFile.read();
	fitsFile.close();
	fileStream.close();		
			
} catch (FitsException e1) {
	
} catch (IOException e) {
	
}
for (int i=0;i<fitsFileHDU.length;i++){

     if (fitsFileHDU[i].getHeader().containsKey("ZIMAGE")){
	     if(fitsFileHDU[i].getHeader().getBooleanValue("ZIMAGE") ){		
                     CompressedImageHDU hdu = (CompressedImageHDU) fitsFileHDU[i];
												
                     ImageHDU uncompressedImage = null;
                     try {
	                    uncompressedImage = hdu.asImageHDU();
                     } catch (FitsException e) {
	     
                     }
              }
        }
}

It fails when I call

hdu.asImageHDU();

stack trace:

Caused by: java.lang.NullPointerException
	at nom.tam.fits.ImageData.parseHeader(ImageData.java:267)
	at nom.tam.fits.ImageData.<init>(ImageData.java:142)
	at nom.tam.fits.ImageHDU.manufactureData(ImageHDU.java:110)
	at nom.tam.image.compression.hdu.CompressedImageHDU.asImageHDU(CompressedImageHDU.java:126)
	at imageLoaders.FitsLinearImageLoaderTask.doInBackground(FitsLinearImageLoaderTask.java:499)

I believe the Fits file originates from Images Plus.

For completeness, the header of all the HDUs:
HDU1 - SIMPLE  =                    T / file does conform to FITS standard             
HDU1 - BITPIX  =                   16 / number of bits per data pixel                  
HDU1 - NAXIS   =                    0 / number of data axes                            
HDU1 - EXTEND  =                    T / FITS dataset may contain extensions            
HDU1 - COMMENT FITS (Flexible Image Transport System) format is defined in 'Astronomy  
HDU1 - COMMENT and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H   
HDU1 - END                                                                             
HDU2 - XTENSION= 'BINTABLE'           / binary table extension                         
HDU2 - BITPIX  =                    8 / 8-bit bytes                                    
HDU2 - NAXIS   =                    2 / 2-dimensional binary table                     
HDU2 - NAXIS1  =                    8 / width of table in bytes                        
HDU2 - NAXIS2  =                 3668 / number of rows in table                        
HDU2 - PCOUNT  =             20671944 / size of special data area                      
HDU2 - GCOUNT  =                    1 / one data group (required keyword)              
HDU2 - TFIELDS =                    1 / number of fields in each row                   
HDU2 - TTYPE1  = 'COMPRESSED_DATA'    / label for field   1                            
HDU2 - TFORM1  = '1PB(6118)'          / data format of field: variable length array    
HDU2 - EXTNAME = 'COMPRESSED_IMAGE'   / name of this binary table extension            
HDU2 - ZIMAGE  =                    T / extension contains compressed image            
HDU2 - ZBITPIX =                   20 / data type of original image                    
HDU2 - ZNAXIS  =                    2 / dimension of original image                    
HDU2 - ZNAXIS1 =                 5494 / length of original image axis                  
HDU2 - ZNAXIS2 =                 3668 / length of original image axis                  
HDU2 - ZTILE1  =                 5494 / size of tiles to be compressed                 
HDU2 - ZTILE2  =                    1 / size of tiles to be compressed                 
HDU2 - ZCMPTYPE= 'RICE_1  '           / compression algorithm                          
HDU2 - ZNAME1  = 'BLOCKSIZE'          / compression block size                         
HDU2 - ZVAL1   =                   32 / pixels per block                               
HDU2 - END                                                                             
HDU3 - XTENSION= 'BINTABLE'           / binary table extension                         
HDU3 - BITPIX  =                    8 / 8-bit bytes                                    
HDU3 - NAXIS   =                    2 / 2-dimensional binary table                     
HDU3 - NAXIS1  =                    8 / width of table in bytes                        
HDU3 - NAXIS2  =                 3668 / number of rows in table                        
HDU3 - PCOUNT  =             21248070 / size of special data area                      
HDU3 - GCOUNT  =                    1 / one data group (required keyword)              
HDU3 - TFIELDS =                    1 / number of fields in each row                   
HDU3 - TTYPE1  = 'COMPRESSED_DATA'    / label for field   1                            
HDU3 - TFORM1  = '1PB(6162)'          / data format of field: variable length array    
HDU3 - EXTNAME = 'COMPRESSED_IMAGE'   / name of this binary table extension            
HDU3 - ZIMAGE  =                    T / extension contains compressed image            
HDU3 - ZBITPIX =                   20 / data type of original image                    
HDU3 - ZNAXIS  =                    2 / dimension of original image                    
HDU3 - ZNAXIS1 =                 5494 / length of original image axis                  
HDU3 - ZNAXIS2 =                 3668 / length of original image axis                  
HDU3 - ZTILE1  =                 5494 / size of tiles to be compressed                 
HDU3 - ZTILE2  =                    1 / size of tiles to be compressed                 
HDU3 - ZCMPTYPE= 'RICE_1  '           / compression algorithm                          
HDU3 - ZNAME1  = 'BLOCKSIZE'          / compression block size                         
HDU3 - ZVAL1   =                   32 / pixels per block                               
HDU3 - END                                                                             
HDU4 - XTENSION= 'BINTABLE'           / binary table extension                         
HDU4 - BITPIX  =                    8 / 8-bit bytes                                    
HDU4 - NAXIS   =                    2 / 2-dimensional binary table                     
HDU4 - NAXIS1  =                    8 / width of table in bytes                        
HDU4 - NAXIS2  =                 3668 / number of rows in table                        
HDU4 - PCOUNT  =             20529066 / size of special data area                      
HDU4 - GCOUNT  =                    1 / one data group (required keyword)              
HDU4 - TFIELDS =                    1 / number of fields in each row                   
HDU4 - TTYPE1  = 'COMPRESSED_DATA'    / label for field   1                            
HDU4 - TFORM1  = '1PB(6001)'          / data format of field: variable length array    
HDU4 - EXTNAME = 'COMPRESSED_IMAGE'   / name of this binary table extension            
HDU4 - ZIMAGE  =                    T / extension contains compressed image            
HDU4 - ZBITPIX =                   20 / data type of original image                    
HDU4 - ZNAXIS  =                    2 / dimension of original image                    
HDU4 - ZNAXIS1 =                 5494 / length of original image axis                  
HDU4 - ZNAXIS2 =                 3668 / length of original image axis                  
HDU4 - ZTILE1  =                 5494 / size of tiles to be compressed                 
HDU4 - ZTILE2  =                    1 / size of tiles to be compressed                 
HDU4 - ZCMPTYPE= 'RICE_1  '           / compression algorithm                          
HDU4 - ZNAME1  = 'BLOCKSIZE'          / compression block size                         
HDU4 - ZVAL1   =                   32 / pixels per block                               
HDU4 - CFAPAT  = 'RG,GB   '           / CFA Pattern                                    
HDU4 - COMMENT Camera Model : Canon EOS 6D                                             
HDU4 - COMMENT Capture Time : Thu Jun 26 02:10:15 2014                                 
HDU4 - COMMENT Shutter Speed : 601.2 sec                                               
HDU4 - COMMENT ISO : 200                                                               
HDU4 - COMMENT F-Number : f/1.$                                                        
HDU4 - COMMENT IP Calibrate - Color Model : MONO                                       
HDU4 - COMMENT IP Calibrate - Use Flat                                                 
HDU4 - COMMENT IP Calibrate - Use Bias                                                 
HDU4 - COMMENT IP Calibrate - Use Dark : auto factor                                   
HDU4 - COMMENT IP Calibrate -   Adaptive: No                                           
HDU4 - END        

Could this be a bug of the library, or am I possibly doing something wrong here, or is this particular FITS file created not according to FITS conventions possibly?

Kind regards,
Mabula Haverkamp

**Comment by ritchieGitHub** [comment]
could you attach the image file? or add it as a pull request to https://github.com/nom-tam-fits/blackbox-images if we may use the image as a test for the future?

**Comment by mabula117** [comment]
Hi ritchieGitHub, 

The FITS files are rather large, and I can't upload one, because I don't have push access.

So I uploaded two of the FITS files to my own server, you can download them here:

[http://www.bulapedia.nl/images/nom-tam-fits/](http://www.bulapedia.nl/images/nom-tam-fits/)

(Both files were created with images plus, data was gathered with different cameras)

**Comment by ritchieGitHub** [comment]
The reason is found ;-) , the BITPIX of the image is set to 20, which is not a legal value. I will see if I can get around this and allow the value of 20.

**Comment by ritchieGitHub** [comment]
Could you try my fix? please use the SNAPSHOT version: nom-tam-fits-1.15.2-SNAPSHOT
you can find it in the SNAPSHOT repository:
```
https://oss.sonatype.org/content/repositories/snapshots/gov/nasa/gsfc/heasarc/nom-tam-fits/1.15.2-SNAPSHOT/
```
Specially if the uncompressed data is correct! If my guesses ;-) are correct then I will release a new version. So please write a comment with your findings!

**Comment by mabula117** [comment]
Hi ritchieGitHub,

Excellent, thank you ritchieGitHub ;-)

yes, the BITPIX value of 20 was suspicious indeed.

Okay, the decompression works correctly now.

But the data output after decompression, using the getkernel() method is in int[][] format, whereas the data should be in 16bits format, so I would think the output should be in short[][] format also? Maybe you guessed the data is in 32bits format? 

Can you alter the 20 bitpix interpretation into 16bit and return the data as short[][]? If so, that would be the correct interpretation I think.

I have compared the data output with the 16bits uncompressed TIFFs that I have and the uncompressed data is the same. 

(The output int[][] arrays have as maximum value 65535, indicating the data is in16bit data range.)

I have uploaded the 16bits uncompressed tiffs to
[http://www.bulapedia.nl/images/nom-tam-fits/](http://www.bulapedia.nl/images/nom-tam-fits/)
as well, so you can compare it if you want.

Screenshot uncompressed TIFF data with stretch:
[http://www.bulapedia.nl/images/nom-tam-fits/TiffOutput16bitsUncompressed.jpg](http://www.bulapedia.nl/images/nom-tam-fits/TiffOutput16bitsUncompressed.jpg)

Screenshot decompressed FITS data with identical stretch:
[http://www.bulapedia.nl/images/nom-tam-fits/FITSOutput16bitsDecompressed.jpg](http://www.bulapedia.nl/images/nom-tam-fits/FITSOutput16bitsDecompressed.jpg
)

**Comment by ritchieGitHub** [comment]
changing the bitpix automatically is not a good idea, that should be the responsibility of the user if he really wants to do that. And in java the maximum value of a short is 32767 because it includes the negative values. And not all users want to use the negative values with an offset.
I will try to make a release next weekend.

**Comment by mabula117** [comment]
Thank you ritchieGitHub, I understand. You are totally right regarding the short range, I know it's stored as signed values. So indeed, the output in this case can only be in int[][] format. Otherwise the library would need to do internal conversion of the data for this exception and that is not a good idea, so I agree.

Thank you for solving this so quickly ;-) It's really helpfull!
