### ISSUE TITLE
PaddingException with FITS image from I-Nova CCD camera produced by I-Nova BatchProcess

### ISSUE THREAD

**Issue by mabula117** [nom-tam-fits/nom-tam-fits#109]
Hi,

I have two FITS files with an image uploaded here:
http://www.bulapedia.nl/images/nom-tam-fits/paddingException/

When I try to load them with the library using:

try {
	InputStream fileStream = new BufferedInputStream(new FileInputStream(imageFile));
	imageFile = null;
	Fits fitsFile = new Fits(fileStream); //associate fits file with stream
	fitsFileHDU = fitsFile.read(); //get all HDUs from this fits File and get entire stream
	fitsFile.close();
	fitsFile= null;
	fileStream.close();		
	fileStream=null;
} catch (FitsException e1) {
	
} catch (IOException e) {
	
}

I get the following stack trace:

nom.tam.fits.PaddingException: Error skipping padding after image
	at nom.tam.fits.ImageData.read(ImageData.java:217)
	at nom.tam.fits.Fits.readHDU(Fits.java:651)
	at nom.tam.fits.Fits.readToEnd(Fits.java:672)
	at nom.tam.fits.Fits.read(Fits.java:598)
	at frameDetails.FitsImageDetails.calculateDetails(FitsImageDetails.java:111)

In the past, the nom-tam-fits library V1.10.0 had no problem with these two Fits files. 

Is this a bug? Or are the FITS files, from the I-Nova Batchprocess, not created according to FITS conventions?

Kind regards,
Mabula Haverkamp

p.s.s feel free to download the 2 fits files for testing purposes.

**Comment by ritchieGitHub** [comment]
I will check them this weekend. (Thanks for the test images!)

**Comment by ritchieGitHub** [comment]
Yes, both images are not legal according the standard, the padding bytes after the image data that fills the required 2880 blocks is missing in both images in one  case 960 bytes are needed as padding and in the other case 1920 bytes are needed as padding to make the images legal. @TomMcGlynn do you thing we should "allow" such missing paddings? It seems we could support that with not much trouble, but on the other side that would further "encourage" supporting illegal files. On the other side we would only allow the input to be illegal, writing would automatically add the padding.

@TomMcGlynn I think that's your call to decide how to handle this. Just say if you would support that or not, I can do the implementation. After that I think we could release another minor version!

**Comment by TomMcGlynn** [comment]
If Mabula wants to be able to read a truncated HDU, this situation is already handled by the FITS library.   The JavaDoc for the PaddingException you describes a method getHDU().  You can get the HDU that wasn't padded with this call. So if you run into an unpadded FITS HDU you can still read the data.  This balances the needs of users to retrieve data that may have been written incorrectly with the desire to ensure that we don't allow invalid FITS data to propagate without warning.  If you are running into these exceptions frequently, the JavaDoc suggests an idiom for reading FITS files.

I haven't looked at this for quite a while, so it's possible this doesn't meet all of the user's needs, but I think this kind of approach is better than handling erroneous files completely transparently.  Maybe we should add something to the error message associated with the PaddingException that reminds users of this approach, but other than that I'd suggest closing this issue.

**Comment by ritchieGitHub** [comment]
Exactly my opinion, I think we missed a spot here. I will try a unit test this weekend, and fix it if nessesary.

**Comment by mabula117** [comment]
Hi ritchieGitHub and TomMcGlynn,

Thank you for your feedback and the solution, If I had properly read the java docs, I should have been able to sort this one out myself, my apologies. I can now read all FITS files that I have from lots of different sources using your library. My compliments ;-) !

The i-Nova files are being read properly using the following code, following the PaddingException:

Fits fitsFile = null;
		try {
			InputStream fileStream = new BufferedInputStream(new FileInputStream(imageFile));
			fitsFile = new Fits(fileStream);
			fitsFileHDU = fitsFile.read(); //get all HDUs from this fits File and get entire stream
			fitsFile.close();
			fitsFile = null;
			fileStream.close();		
			fileStream = null;
			
		} catch (PaddingException e3) {
			// if images aren't correctly padded, (iNOVA software)
			// we can still read the HDUs properly
			// this exception is to indicate, that these files are wrongly created
			
			try {
				
				fitsFile.addHDU(e3.getTruncatedHDU());
				fitsFileHDU = fitsFile.read(); // read again all HDUs including the truncated HDU
				
			} catch (FitsException e) {
				
				FitsExceptionHandler.showFitsException(e, imageFile);
				this.cancel(true);
			}
			
			
		} catch (FitsException e1) {
			
			FitsExceptionHandler.showFitsException(e1, imageFile);
			this.cancel(true);
			
		} catch (IOException e2) {
			
			IOExceptionHandler.showIOException(e2, imageFile);
			this.cancel(true);
			
		} 
		fitsFile = null;

**Comment by ritchieGitHub** [comment]
great, but I still wan't to check if we can allow the other method as well. but with an appropriate  error message.
Thanks for your reports! every found  bug / problem improves the library!

**Comment by attipaci** [comment]
Hi Mabula,

I assume this is another case that is fixed by `FitsFactory.setAllowTerminalJunk(true)`. If so, I will close this issue soon. Let me know if I should keep it open.
