### ISSUE TITLE
RFE: skipping tests when images cannot be downloaded

### ISSUE THREAD

**Issue by keszybz** [nom-tam-fits/nom-tam-fits#111]
I'm building an official package for Fedora. In the distro build system, packages are build without network access. This means that the test images would have to be pre-downloaded for the tests to succeed. But the blackbox-images repo is big (tar.gz is 600MB), which is too much to put in the source rpm. I'd like to skip the tests in this case.

I used the following hacky patch:
```diff
diff --git a/src/test/java/nom/tam/fits/util/BlackBoxImages.java b/src/test/java/nom/tam/fits/util/BlackBoxImages.java
index 0508d5c32c..b5de99a5e8 100644
--- a/src/test/java/nom/tam/fits/util/BlackBoxImages.java
+++ b/src/test/java/nom/tam/fits/util/BlackBoxImages.java
@@ -86,6 +86,8 @@ public class BlackBoxImages {
             }
 
         }
+
+        org.junit.Assume.assumeTrue(false);
         throw new UnsupportedOperationException("could not get blackbox image from anywhere");
     }
```

This works, but is not that nice. It would be great if you could incorporate some way to either skip those tests for which data is unavailable and cannot be downloaded.

**Comment by ritchieGitHub** [comment]
Ok, I think a build profile that skips these tests would do the trick

**Comment by ritchieGitHub** [comment]
Will be done this weekend

**Comment by keszybz** [comment]
Thanks!

**Comment by ritchieGitHub** [comment]
please try using the profile skipBlackBoxImages, that should now skip all blackbox image tests

**Comment by attipaci** [comment]
I assume this issue can be closed now. If not, feel free to reopen.
