### ISSUE TITLE
ImageHDU tiler corrupts values after 2GB worth of data

### ISSUE THREAD

**Issue by cporte** [nom-tam-fits/nom-tam-fits#112]
Used version: 1.15.1
Considering a file, single HDU with a 2 axis array, 326136x1000 float64 values (file is 2.43 GiB) with following code
```
ImageHDU hdu = (ImageHDU) f.getHDU(0);
ImageTiler tiler = hdu.getTiler();
double[] values = (double[]) tiler.getTile(new int[] { 0, 231607 }, new int[] { 1000, 1 });
System.out.println(((double[][]) hdu.getKernel())[800][231607]);
System.out.println(values[800]);
System.out.println(((double[][]) hdu.getKernel())[850][231607]);
System.out.println(values[850]);
```

Expected output:
2.8784133518557868E-5
2.8784133518557868E-5
4.195905993997342E-5
4.195905993997342E-5

Current output:
2.8784133518557868E-5
2.8784133518557868E-5
4.195905993997342E-5
1.64931512039243E93

The corruption starts somewhere in the row 823, which is coherent with the 2GB threshold (822*8*326136 < 2GiB < 823*8*326136)

**Comment by ritchieGitHub** [comment]
sorry for the late replay, I was on a "holliday" next weekend I will take try to reproduce this (and fix it ;-) )

**Comment by ritchieGitHub** [comment]
the problem was an integer overflow in the image tiler, could you try the snapshot? 1.15.2-SNAPSHOT

**Comment by cporte** [comment]
Works perfectly now, thanks!
