### ISSUE TITLE
Implement a markSupported() method

### ISSUE THREAD

**Issue by olebole** [nom-tam-fits/nom-tam-fits#114]
Another problem that came up during the update of [Starjava](https://github.com/Starlink/starjava) to the latest `nom.tam.fits`:
The new version of the `nom.tam.util.ArrayDataInput` interface requires the implementation of the `mark()` and `reset()` methods, like `java.io.BufferedInputStream`. However, the `ArrayDataInput` interface lacks the `markSupported()` method, so that one cannot check the support before trying it out.

Would it be possible to add `markSupported()` here?

@mbtaylor may also be interested in this.

**Comment by mbtaylor** [comment]
This suggestion comes out of a comment I made to @olebole when comparing the `ArrayDataInput` interface with the `java.io.InputStream` API - the existence of `markSupported` alongside `mark`/`reset` methods allows an implementation to avoid implementing mark/reset functionality (which may be impractical or efficient for certain implementations).  However, adding a `markSupported` method to the existing `ArrayDataInput` interface would be problematic, in that it's backwardly incompatible in a hard-to-notice way.  Legacy code that assumes mark/reset functionality is present could break when faced with a newer `ArrayDataInput` instance that doesn't support it.  So I'm not sure that the API change suggested here would be a good idea.

**Comment by olebole** [comment]
The insertion of mark/reset already broke the compatibility, and the `reset()` [documentation](http://nom-tam-fits.github.io/nom-tam-fits/apidocs/nom/tam/util/ArrayDataInput.html#reset%28%29) explicitly refers to the contract in the `InputStream` API (which includes `markSupported()`). To me, the implementations of `RandomAcess` (which extends `ArrayDataInput`) in Starjava/fits (namely [`uk.ac.starlink.fits.MappedFile`](https://github.com/Starlink/starjava/blob/master/fits/src/main/uk/ac/starlink/fits/MappedFile.java) and [`uk.ac.starlink.fits.MultiMappedFile`](https://github.com/Starlink/starjava/blob/master/fits/src/main/uk/ac/starlink/fits/MultiMappedFile.java)) are good examples where the mark/reset functionality is not needed (yet) and (at least for `MultiMappedFile`) not trivial), which would require either to split this functionality from the other methods (like `read()`) in `DataInput`, or to allow (and flag) the implementation to be missing.

**Comment by mbtaylor** [comment]
OK well I'm happy to leave it to the nom-tam-fits developers to make this call.

**Comment by ritchieGitHub** [comment]
Lets see if I can find a loophole ;) this weekend. It could take 2 weekends because I already hav a full program ;) . But I will do it as fast as possible.

**Comment by ritchieGitHub** [comment]
sorry missed this one for the release, will try to add it very soon

**Comment by attipaci** [comment]
Is there interest from any of you in working on this issue for an upcoming maintenance release?

**Comment by mbtaylor** [comment]
OK - see PR attipaci/nom-tam-fits#8. I think that covers it.
