### ISSUE TITLE
Scientific notation not being used with decimal numbers

### ISSUE THREAD

**Issue by wcleveland** [nom-tam-fits/nom-tam-fits#117]
A change made back in Mar 18, 2016 prevents the writing of scientific notation within the FITS file. This was caught by a file verifier upstream from my server, and I'll need to come up with a method to create a float or double header card using scientific notation. 

I will also add the ability to designate the letter being used to signify the exponent, since files made with Astro.FITS.CFITSIO use '12.34D-10' notation instead of '12.34E-10' notation, and the verifier actually checks for this (sigh).

The scientific notation will comply with the format described in FITS standard 3.0aa Section 4.2.4.

I'll have a pull request ready shortly.

**Comment by ritchieGitHub** [comment]
thanks!

**Comment by wcleveland** [comment]
Fixed with pull request #120 and #123
