### ISSUE TITLE
FITS read problem

### ISSUE THREAD

**Issue by AstroPixelProcessor** [nom-tam-fits/nom-tam-fits#139]
Hi there,

I am the main developer of Astro Pixel Processor, a commercial Deep Sky image processing application. And I use your library to read/write fits files.

I just received 2 fits frames from one of my software users and the library throws a fits read error. I strongly suspect that the fits frames are not created properly. Either the header or the image data is not stored properly I think.

My question is, is there a way to still load the image data without problems? Other software, like Fits Liberator simply shows the image data whereas nom.tam.fits throws an error and I can't load the image data.

The 2 files:
https://apastropixelprocessordl.s3.eu-central-1.amazonaws.com/FITS/Lagoon008.fits
https://apastropixelprocessordl.s3.eu-central-1.amazonaws.com/FITS/B_725.897_3x60.fits

I simply try to read it with:

BasicHDU<?>[] fitsFileHDU = fitsFile.read();

Fits fitsFile is received from an Inputstream 

If you want to see all my code, please let me know.

This is the thrown error, using nom-tam-fits-1.15.3-20170716.141105-5.jar :

nom.tam.fits.FitsException: IO error: java.io.IOException: Invalid FITS Header
	at nom.tam.fits.Fits.readToEnd(Fits.java:685)
	at nom.tam.fits.Fits.read(Fits.java:597)

Kind regards,

Mabula Haverkamp
mabula@astropixelprocessor.com
https://www.astropixelprocessor.com/

**Comment by attipaci** [comment]
Hi Mabula!

Sorry for the delayed response. I just took over interim management of this repo from Ritchie.

The short answer is that the FITS files are a bit corrupted, which is why the library throws an error. You can work around it by calling `FitsFactory.setAllowTerminalJunk(true);` prior to reading. This enables a more tolerant reading, and I verified that I could read both files you referenced. :-)

Let me know if you want to follow up more. I'll leave the ticket open for a bit longer...

**Comment by attipaci** [comment]
I have made a change (see PR above) to make the error more informative (with the suggestion to set `FitsFactory.setAllowTerminalJunk(true)`, and with an extended stack trace to help developers).

**Comment by AstroPixelProcessor** [comment]
Hi Atilla,

Thank you very much for your reaction. Indeed, using FitsFactory.setAllowTerminalJunk(true) fixed it for me quite a while ago, but still thanks for following up ;-)

Mabula

**Comment by attipaci** [comment]
I'm glad. Feel free to come back here any time with questions or more. As long as I am managing this repo, I promise you won't have to wait another 2 years for an answer... :-D

And, if you ever feel like contributing code for fixes or new features that you felt were important, that would be great too. It's a community maintained lib, without a lead developer really (I'm only supervising, for now). PRs are always welcome!

**Comment by AstroPixelProcessor** [comment]
Thank you very much Atilla, glad to see that the library is again being worked on ;-) actively !

I still need to further look at this one that I submitted:
https://github.com/nom-tam-fits/nom-tam-fits/issues/116

Another important feature for me and the future of FITS files and this library would be that we could create pictures with more pixels than the 2^32 = 4.3 Gigapixels. Right now, because of this limit, Huge panaroma's/mosaics can't be created with this library or is there a way that you know possibly?

If I get time to help with the library I will let you know ;-)
Mabula
