### ISSUE TITLE
How to determine type of existing value of HeaderCard?

### ISSUE THREAD

**Issue by supermartzin** [nom-tam-fits/nom-tam-fits#14]
Hi again!

Is there any way how to find out the exact type of value of header card that already exists in the header?
I'm aware of ```Header``` methods ```getIntValue()```,```getDoubleValue()``` and so on, but from their result I'm not able to recognize if it's the actual value or if it's default value of that type (```boolean``` for example).
Unfortunately I'm not able to determine it neither from ```HeaderCard``` class and its methods.

My problem is that I'm implementing functionality of replacing old keyword for new one. Now I'm using this piece of code:
```java
HeaderCard oldCard = header.findCard(oldKeyword);
HeaderCard newCard = new HeaderCard(newKeyword, oldCard.getValue(), oldCard.getComment());
header.updateLine(oldKeyword, newCard);  // update old card with new one
```
but with ```getValue()``` method I am only able to get stringified value of old card. Problem is when value is originaly double, boolean or other besides the String, the updated value will be always String.

Do you have any idea how could I do this?
Thanks in advance for advice :)

**Comment by ritchieGitHub** [comment]
at the moment you can only analyse the String to determan the value type. But let me see if i can do something better.

**Comment by ritchieGitHub** [comment]
ok, just deployed a version that supports a HeaderCard.valueType() function that determinates the class type of the value.

**Comment by supermartzin** [comment]
Thanks man, you're great!

**Comment by supermartzin** [comment]
I found an issue in ```valueType()``` method - value **186.0** matches as BigInteger. 
Looking at your source code you are using an regex which is not completely correct because it matches also double values. 
Here is that regex improved to match only integral values:
```regex
^[0-9]+$
```

**Comment by ritchieGitHub** [comment]
No that's not the reason, matches() does add the ^ and$ implicitly. I was optimizing to much :-)  sorry will correct it tomorrow morning. Together with a <T> T getvalue(Class<T> clazz) that takes a class as a parameter of the type you want the value in.

**Comment by supermartzin** [comment]
Great, thank you! :)
And what is a problem in this case if it's not a regex?

**Comment by ritchieGitHub** [comment]
ok, the snapshot is published. but not that to copy a card the better way is to
```java
new HeaderCard(hc.toString()); 
```
that keeps everthing the same, because there are some special cases like long-string handling where a very long string is splitted over multiple cards and uses the comment area for the value.

Please give a hint when your task is done, then we can release the 1.12.1 version.

**Comment by supermartzin** [comment]
>ok, the snapshot is published. but note that to copy a card the better way is to
>```java
new HeaderCard(hc.toString()); 
```
>that keeps everthing the same, because there are some special cases like long-string handling where a very long string is splitted over multiple cards and uses the comment area for the value.

But is it also correct way how to change only keyword of that card? Because ```HeaderCard.toString()``` will copy the whole card, not only the value so I cannot change the keyword in this case.

**Comment by ritchieGitHub** [comment]
Correct, just wanted to give a watch out :-)

**Comment by supermartzin** [comment]
But anyway, in case that the card contains long-string what would you recommend to do in order to change only the keyword? Now I'm doing it the way I described in first post but I'm just wondering if it covers all cases of value length.
Thanks :)

**Comment by ritchieGitHub** [comment]
If you want to support long-strings (not many tools do) you will have to do it in some special way. I will get back to you tomorrow.

**Comment by supermartzin** [comment]
Thanks for advice.

**Comment by ritchieGitHub** [comment]
just opened an other issue to make the access of longstring's in the iterator easyer, so I will close this issue
