### ISSUE TITLE
Problem with "CONTINUE" keyword

### ISSUE THREAD

**Issue by ChristianWSmith** [nom-tam-fits/nom-tam-fits#140]
I have noticed a problem with the “CONTINUE” keyword.  When reading in an existing fits file with the keyword present and writing it back out, the resultant file will not have the standard 2 spaces that are supposed to follow the keyword per the FITS documentation.
I’ve included a test class that can be used to reporduce this problem.  I used a file from this repo (https://github.com/nom-tam-fits/nom-tam-fits/blob/master/src/test/resources/nom/tam/image/provided/issue49test.fits) as input.

[FitsTester.java.gz](https://github.com/nom-tam-fits/nom-tam-fits/files/3726314/FitsTester.java.gz)

**Comment by ChristianWSmith** [comment]
`import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.File;

import nom.tam.fits.Fits;
import nom.tam.fits.FitsException;
import nom.tam.fits.HeaderCardException;
import nom.tam.util.BufferedDataOutputStream;
import nom.tam.util.BufferedFile;


public class FitsTester
{
        public static void main(String args[])
        {
                if (args.length != 2)
                {
                        System.out.println("Usage: java -cp nom-tam-fits.jar FitsTester <input_file> <output_file>");
                        System.exit(1);
                }
                try
                {
                        readAndWrite(args[0], args[1]);
                }
                catch (Exception e)
                {
                        e.printStackTrace();
                }
        }


        private static void readAndWrite(String inFileName, String outFileName) throws FitsException, HeaderCardException, IOException, FileNotFoundException
        {
                Fits originalFitsFile = new Fits(inFileName);

                originalFitsFile.read();

                FileOutputStream outputFileStream = new FileOutputStream(outFileName);
                BufferedDataOutputStream bufferedOutputStream = new BufferedDataOutputStream(outputFileStream);
                originalFitsFile.write(bufferedOutputStream);

                bufferedOutputStream.flush();
                bufferedOutputStream.close();

                outputFileStream.flush();
                outputFileStream.close();
                originalFitsFile.getStream().close();
        }
}`

**Comment by attipaci** [comment]
Thanks for pointing this out. I've just began taking over managing this repo (hence the much delayed response). Would you be interested in providing the fix, and include your test in with the other unit tests? If so, feel free to fork the repo and make your changes, and make a pull request when ready to integrate. Alternatively, I can look into fixing it myself over the next few weeks. Let me know what you prefer...

**Comment by attipaci** [comment]
It looks to me that the issue may already be resolved. If you take a look at `HeaderCard`, and the `writeLongStringValue()` method in it, is clear that all lines stating with CONTINUE actually begin with `CONTINUE_CARD_PREFIX`, which is defined in the same source files as the literal CONTINUE, followed by the requisite 2 spaces, and a single quote... If you don't think that resolves it, let me know. Otherwise, I'll mark this as closed...

**Comment by attipaci** [comment]
Closing because I think this has been solved a while back. We can reopen if turns out to be an issue still...
