### ISSUE TITLE
Add lookup for HDU by extension name and version

### ISSUE THREAD

**Issue by at88mph** [nom-tam-fits/nom-tam-fits#145]
In order to specify random access lookup for tiling (cutouts), it would be very useful to use a common syntax to specify the extensions that a user would like to tile from:

### Extension 9
`[9][100:300]`

### Extension {SCI,2}
`[SCI,2][100:300]`

Obtaining by index is already supported.  This enhancement is just to lookup by name (`EXTNAME`) and version (`EXTVER`).

**Comment by attipaci** [comment]
That all sounds reasonable. I myself have not used tiling, so I'm not familiar with that part of the lib. Would you like to make the proposed changes on a fork, and I create a pull request when ready? (Also, don't forget to add unit tests too that cover the changes and/or any new code). 
-- A.
