### ISSUE TITLE
Unwanted quote manipulation for string headers

### ISSUE THREAD

**Issue by mbtaylor** [nom-tam-fits/nom-tam-fits#148]
The `nom.tam.fits.HeaderCard` constructor for String values includes this code:

    if (value.startsWith("'")) {
        if (value.charAt(value.length() - 1) != '\'') {
            throw new HeaderCardException("Missing end quote in string value");
        }
        value = value.substring(1, value.length() - 1).trim();
    }

I think it's trying to be helpful in case you've pre-quoted a string value, though this behaviour is not documented.  One consequence is that e.g.

    new HeaderCard("TUNIT67", "'electron'.s**-1", "Units for phot_g_mean_flux");

fails with an exception.  The only way you can set a card with that value, if you know the trick, is to wrap it in single quotes:

    new HeaderCard("CARD", "''electron'.s**-1'", "comment");

in which case the code strips out the outer quotes.  This behaviour is surprising and hard to work with.  I'd like to remove the above stanza/behaviour altogether, but I don't know whether other code depends on it.

**Comment by attipaci** [comment]
I tend to agree that that's an over-zealous check. I'd be in favor of its removal, provided it does not break any of our existing test cases. I'll look into it over the next week or two. Feel free to remind me if you don't hear back from me in say 2 weeks, or feel free to preempt me with a pull request... :-)

**Comment by attipaci** [comment]
OK, now that I slept on it a bit, I know why the check is there -- it's because in the FITS convention, the string values must be quoted with single quotes when the header is wrotten. So when you parse the header from a FITS file, you want to remove those quotes. However, if you are creating a `HeaderCard` with a `String` value argument (as in your example), it should be handled separately (with no checks), but right now it's not...

**Comment by attipaci** [comment]
Hi Mark,

I have started on this issue, and I think it is more or less resolved. I want to sleep on it to make sure I am not forgetting anything and that I am testing for various possibilities. I'll put it on a branch on my fork, so you can take a look also. Alternatively, I can just pull my changes into the mainline, and you can then see if you want to do any add-on work after that...

**Comment by mbtaylor** [comment]
@attipaci, thank you for this, it passes my unit tests now.  I haven't tested it in all situations (e.g. long string values) but it looks OK to me, apart from the minor review comment I made on the PR.
