### ISSUE TITLE
Active development?

### ISSUE THREAD

**Issue by vforchi** [nom-tam-fits/nom-tam-fits#150]
Hi,

I was just wondering if there is any active development going on in this repository. The last commit is 2 years old and there are a number of bugs that have not been addressed.

Cheers,
Vincenzo

**Comment by ritchieGitHub** [comment]
I am sorry but my time is very limited at the moment... There is an active fork somewhere. Maybe someone wants to take over?

Von meinem Huawei-Telefon gesendet


-------- Ursprüngliche Nachricht --------
Von: Vincenzo Forchì ***@***.***>
Datum: Mi., 7. Juli 2021, 14:34
An: nom-tam-fits/nom-tam-fits ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [nom-tam-fits/nom-tam-fits] Active development? (#150)

Hi,

I was just wondering if there is any active development going on in this repository. The last commit is 2 years old and there are a number of bugs that have not been addressed.

Cheers,
Vincenzo

**Comment by vforchi** [comment]
The only active fork I could find is [OpenCADC](https://github.com/opencadc/nom-tam-fits)

**Comment by attipaci** [comment]
Hi! 

I am _de facto_ taking over interim management of the repo from Ritchie (who has done an amazing job getting it off the ground and organized!). 

As per your question, it depends on how you define 'active development'. I'm certainly keen to keep the package in working order, and to provide bug fixes and/or various targeted improvements. I will not have the time and energy to oversee any big overhaul or development. But, if you make pull request, I promise to pay attention to them. :-)

-- A.

**Comment by vforchi** [comment]
That's great news, thanks.
