### ISSUE TITLE
Package nom-tam-fits-1.16.0 depends on javax.annotation-api-1.3.2

### ISSUE THREAD

**Issue by bogdanni** [nom-tam-fits/nom-tam-fits#229]
`javax.annotation` doesn't seem to be used in the source code though.

**Comment by attipaci** [comment]
Hi Bogdan!

The dependence should have scope set to `provided`, which means it should only apply for compiling and test, but not as a regular runtime dependence. If that's not how it is being applied, then that would certainly be a mistake. However, I think we can further restrict it to be purely a `compile` dependence. I'll make the change for the next release... Let me know if you think there is more to be done, or if you find other problems. -- Multumesc!
