### ISSUE TITLE
hdu meta data extraction

### ISSUE THREAD

**Issue by ritchieGitHub** [nom-tam-fits/nom-tam-fits#25]
every hdu has some static methods, that are "describing" the hdu type.

```
encapsulate(Object)
isData(Object)
isHeader(Header)
manufactureData(Header)
manufactureHeader(Data)
```

if would be good to collect them in a kind of meta object to move the static methods to an instance where inheritance can be used. A good design pattern has to be found for this.

**Comment by JonCook** [comment]
I fancy contributing. Maybe I could have a go at this??

**Comment by ritchieGitHub** [comment]
I think this one is to big for a starter, if you want to help maybe take a go at #19 ?
