### ISSUE TITLE
Include Header warnings in Header.setParserWarningsEnabled

### ISSUE THREAD

**Issue by harmanea** [nom-tam-fits/nom-tam-fits#257]
I was excited that the 1.16.0 release included the `Header.setParserWarningsEnabled` option but I was really confused why this toggle does not apply to the `Header` logger as well.

For instance, I would like to suppress the duplicate card warning when parsing a header.

Was this overlooked or is there a reason why this is not the case?
Either way, is there any chance this might get implemented?

**Comment by attipaci** [comment]
It would make sense for the errors about duplicate cards to be controlled by the same setting. I can make that change for the next release (1.16.1, expected next month). 

Not all header warnings are parsing related though. To silence all warnings from `Header` you can control them via `Logger.setLevel()` (you can get the right `Logger` instance via `Logger.getLogger(Header.class.getName());`)...

Does that make sense?

**Comment by harmanea** [comment]
Sorry for the *very* late reply.

Your suggestion works great for now, I'll switch back once the release is out.
Feel free to close this issue.

Thank you!
