### ISSUE TITLE
Problems with multidimensional strings

### ISSUE THREAD

**Issue by TomMcGlynn** [nom-tam-fits/nom-tam-fits#28]
Looks like BinaryTable is not handling arrays of strings as elements properly.   Seems to have done so in the past. The problem seems to be that in changing some of the ArrayFuncs capabilities there was an assumption that flatten would reference only primitive arrays -- which is almost but not quite true.  We need to flatten String arrays also.  The initial problem is that there is a null exception when we look for the appropriate PrimitiveArrayCopierFactory in the FACTORIES hash, but I don't know if that's the extent of the issue.

Not sure what the best approach is here.  Could just add in String/String in the FACTORIES hash, but in principle I think flatten should work for any kind of object, though it will only be used for Strings currently.  Maybe could have an Object/Object instance which throws an IllegalArgumentException if the input and output object types are different?  Or just let it run into a runtime cast exception then?

**Comment by ritchieGitHub** [comment]
now included a generic copier in the factory, that will fail if the objects are not compatible.
