### ISSUE TITLE
Javadoc in Maven repository?

### ISSUE THREAD

**Issue by supermartzin** [nom-tam-fits/nom-tam-fits#30]
Hi,

I would like to ask if you're also publishing a **javadoc** to Maven repository because in IntelliJ IDEA  - Maven plugin I am trying to download those but with no result.

Thanks!

**Comment by ritchieGitHub** [comment]
of course, just forgot it for the last snapshot. Is corrected now, please try and confirm it. During the last few day we have done a lot for stability, and wrote many many unit test  so we cover over 90% now, a confirmation that your program is still running as expected would be great!

**Comment by supermartzin** [comment]
Thanks, I noticed the unit tests activity in your commits. My program is still running with no problems so far.

Although I have one comment about deprecation of `Cursor.add(String, HeaderCard)` method. It would cause no harm if you explicitly mention the replacing method in javadoc, I assume it's `Cursor.add(HeaderCard)` ?

**Comment by ritchieGitHub** [comment]
Yes, that is it. Will be in the javadoc  as soon as I have time again (next weekend)

**Comment by supermartzin** [comment]
Thanks a lot.
