### ISSUE TITLE
collect requests for the upcomming FITS standard

### ISSUE THREAD

**Issue by ritchieGitHub** [nom-tam-fits/nom-tam-fits#33]
This issue is to collect a list of notes to the upcomming standard and the things we wan't to propose there.
- the long string adaptions like making room for longer comments by splitiing up strings.
- long values and comments for non string values (more precission by using BigDecimal / BigInteger) 

@TomMcGlynn any Ideas what to bring in?

**Comment by TomMcGlynn** [comment]
There are several issues with the various proposals that are being 
reviewed that would have impact on the library and I plan to make a 
number of comments when I get back to work on Thursday.  My initial 
impression is that at least one and possible two of the conventions 
should not be adopted into the standard, but I've not had a chance to 
consider them particularly in the light of our library.   Why do these 
things come out when I'm on vacation!

Richard van Nieuwenhoven wrote:

**Comment by ritchieGitHub** [comment]
just the links the current discussions:

https://listmgr.nrao.edu/pipermail/fitsbits/2015-June/thread.html
https://listmgr.nrao.edu/pipermail/fitsbits/2015-July/thread.html

**Comment by attipaci** [comment]
I assume this issue can be closed. If not, feel free to reopen it again.

On a related note, version 1.16 adds support for long comments with long strings (see #173).
