### ISSUE TITLE
Rare NPE with writing of FPACKed files.

### ISSUE THREAD

**Issue by keastrid** [nom-tam-fits/nom-tam-fits#341]
Sometimes when writing an FPACKed HDU, an NPE is thrown due to compressOptions being null, despite being set.

This isn't something I can reliably reproduce (only occurred once for me), though another was able to reproduce it several times with the export of multiHDU files.

The solution we ended up with that seems to work is changing `nom.tam.image.compression.tile.TiledImageCompressionOperation#initializeCompressionControl` to 

```java
private void initializeCompressionControl() {
        if (this.compressorControl == null || imageOptions == null) {
            this.compressorControl = CompressorProvider.findCompressorControl(this.quantAlgorithm, this.compressAlgorithm, getBaseType().primitiveClass());
            if (this.compressorControl == null) {
                throw new IllegalStateException("Found no compressor control for compression algorithm:" + this.compressAlgorithm + //
                        " (quantize algorithm = " + this.quantAlgorithm + ", base type = " + getBaseType().primitiveClass() + ")");
            }
            initImageOptions();
        }
    }
```

[Log](https://gist.github.com/keastrid/a23e3b6ba5719f78fe71208c40803d40)

**Comment by attipaci** [comment]
Thanks for the solution @keastrid. I'll make sure to include that in the next update (around December 15). Do you want to make a PR with the fix, or shall I?

**Comment by keastrid** [comment]
Went ahead and made a PR.
