### ISSUE TITLE
Enable streaming output for tiling

### ISSUE THREAD

**Issue by at88mph** [nom-tam-fits/nom-tam-fits#355]
Related to #282 and #100 

Slicing a tile from a large FITS file will produce an `OutOfMemoryException`, which is particularly problematic when serving data on the web.  Ideally, a cutout `Fits` object could be constructed from a source `Fits` object without reading anything but the base HDU object(s) into memory.  A pseudo code example of what I'm proposing:

```java
     Fits source = new Fits(myFile);
     Fits output = new Fits();
     ImageHDU imageHDU = source.getHDU(1);
     Header tileHeader = adjustHeaderToTile(imageHDU.getHeader()); // Correct the CRPIXn and other headers to match the new dimensions.
     int[] tileStarts = new int[]{10, 10};
     int[] tileLengths = new int[]{45, 60};
     if (overlap(imageHDU.getData())) {
         StreamingTileImageData streamingTileImageData = new StreamingTileImageData(tileHeader, imageHDU.getTiler(),
                                                                                    tileStarts, tileLengths);
         output.addHDU(FitsFactory.hduFactory(tileHeader, streamingTileImageData));
     }
     output.write(outputStream);  // The cutout happens at write time!
```

**Comment by attipaci** [comment]
Hi @at88mph ,

I will check and merge this for 1.18.0 (slated for a 6/15 release), after 1.17.1 is released (right now still held up by a blocking bug).
