### ISSUE TITLE
Checksum/Datasum calculation is wrong for larger files

### ISSUE THREAD

**Issue by Pharisaeus** [nom-tam-fits/nom-tam-fits#367]
Checksum/Datasum calculation gives wrong results for bigger files. From a bunch of quick tests it seems that for files below ~16MB the results were correct but above that the the datasum is incorrect (according to `fitsverify` and to `astropy` and also to nom.tamfits version `1.15.2` we've been using before).

A simple sanity check 1 for file https://archive.eso.org/dataset/ADP.2022-12-14T08:59:35.450 (16MB, can be downloaded directly from https://dataportal.eso.org/dataPortal/file/ADP.2022-12-14T08:59:35.450 )
```java
        try (var fits = new Fits("ADP.2022-12-14T08:59:35.450.fits")) {
            System.out.println(fits.calcDatasum(1));
        }
```

the result is: `3469480134` while:

```python
    f = fits.open("ADP.2022-12-14T08:59:35.450.fits")
    print(f[1]._calculate_datasum())
```

gives `3146076830`, and similar value is outputted by older version of `nom-tam-fits` when running:

```java
        try (var fits = new Fits("ADP.2022-12-14T08:59:35.450.fits")) {
            fits.read();
            fits.setChecksum();
            fits.write(new File("ADP.2022-12-14T08:59:35.450_copy.fits"));
        }
```
and checking the datasum keyword in the file. This is not specific to the file I mentioned, I got the same results for other files, as long as they were slightly bigger. For small files it seemed ok (which would explain why unit tests of nom-tam-fits don't fail - the test files in resources are very small)

**Comment by attipaci** [comment]
It's definitely troubling..

 My guess is that somehow the carry bits aren't being dealt with properly, or else that it's a signed/unsigned type issue. Maybe you can help by comparing the `nom.tam.fits.utilities.FitsCheckSum.java` with the example code provided in the [checksum specification document](https://fits.gsfc.nasa.gov/registry/checksum/checksum.pdf).

Apart from slightly rearranged code, I don't see any deviation from the prescription. Of course, unlike C Java has no `unsigned int`, and hence we use `long` instead to avoid signedness, and the `>>>` operator to bit-shift as if an unsigned value...

**Comment by attipaci** [comment]
It looks like only the checksumming of the data directly from the file is incorrect. If the data is first loaded into RAM, and then checksummed, the result is the expected `3146076830`...

**Comment by attipaci** [comment]
Proposed fix in the PR above.
