### ISSUE TITLE
Cache randomValues for dithering

### ISSUE THREAD

**Issue by keastrid** [nom-tam-fits/nom-tam-fits#407]
We've been looking at speeding up the reading of FITS files, and found what seems to be an easy speedboost.

`QuantizeProcessor.DitherFilter#initRandoms` is run for every DitherFIlter creation on every worker thread. These values don't seem to change, and from some testing making the field static has no effect on the resulting image, but has improved the opening time. For a stack of 100 LCO images is saves about 2 seconds on my machine.

Wanted to discuss this change with with you to see if there are any traps with making the field static, or otherwise sharing the the result.

**Comment by attipaci** [comment]
I think you are absolutely correct. These are static values that should be initialized only once. Would you like to submit a PR to fix, or should I?
