### ISSUE TITLE
Stream reading regression in 1.18.0-rc1 through rc3

### ISSUE THREAD

**Issue by attipaci** [nom-tam-fits/nom-tam-fits#420]
From @keastrid:

@attipaci I think the recent commits introduced a regression to table reading.

Trying to get the hdu array results in the following exception:
```
May 22, 2023 9:07:47 PM nom.tam.fits.Header forceEOF
WARNING: Junk detected at -1.
nom.tam.fits.FitsException: Not a proper FITS header:  at -1
	at nom.tam.fits.Header.checkFirstCard(Header.java:2124)
	at nom.tam.fits.Header.read(Header.java:1579)
	at nom.tam.fits.Header.readHeader(Header.java:170)
	at nom.tam.fits.Fits.readHDU(Fits.java:1005)
	at nom.tam.fits.Fits.readToEnd(Fits.java:1045)
	at nom.tam.fits.Fits.read(Fits.java:956)
```

It is also only finding 2 of the 4 hdus. The file is available [here](https://mast.stsci.edu/api/v0.1/Download/file/?uri=mast:TESS/product/tess2021175071901-s0040-0000000008266786-0211-s_tp.fits)

**Comment by attipaci** [comment]
Hi @keastrid,

OK, so this seems to be a problem only when reading from a stream, and from a file. I think it's likely due to handling a `read()` returning 0 not being handled right...

**Comment by attipaci** [comment]
The proposed fix is in PR #421. It seems to fix the problem on my end.

(For extra fun my Eclipse code cleanup started acting up recently, mucking up everything when I save files, regardless of what preferences I set. It's driving me crazy -- but that's why my commits always have more changes than strictly necessary. It's really annoying...)

**Comment by keastrid** [comment]
Thanks for the quick fix, this seems to work! I had forgotten that our IO goes through a stream.

**Comment by attipaci** [comment]
Thanks for catching it @keastrid . It would have been a real bummer to slip up on something like this after all the work that went into this next release. Let me know if you find anything else. If not, I'll stick to the 6/15 release date to make 1.18.0 official...

**Comment by attipaci** [comment]
(BTW, I managed to tame my eclipse after all -- it was missing a jar for annotations, and that apparently caused it to go totally wild when processing source file on save. Weird...)
