### ISSUE TITLE
use standard nio ByteBuffer instead of own implementation

### ISSUE THREAD

**Issue by ritchieGitHub** [nom-tam-fits/nom-tam-fits#45]
nom.tam.util.BufferPointer
nom.tam.util.BufferEncoder
nom.tam.util.BufferDecoder

should be replaced by java.lang.ByteBuffer
maybe in combination with:
ByteBuffer#asCharBuffer()
ByteBuffer#asDoubleBuffer()
ByteBuffer#asFloatBuffer()
ByteBuffer#asIntBuffer()
ByteBuffer#asLongBuffer()
ByteBuffer#asReadOnlyBuffer()
ByteBuffer#asShortBuffer()
these can read an write whole arrays at once.

**Comment by attipaci** [comment]
This is pretty much delivered in 1.16, where the entire FITS IO went through an overhaul (see #189). The new encoder/decoder classes (e.g. `ArrayEncoder` -> `FitsEncoder`) use `ByteBuffer` internally (and it shows in performance), while `BufferPointer` is entirely retired (kept around for back compatibility only.
