### ISSUE TITLE
refactor checksum calculation

### ISSUE THREAD

**Issue by ritchieGitHub** [nom-tam-fits/nom-tam-fits#53]
as noted in #26 the calculation of the checksum is very "roundabout" and should be refactored to a more simple approach. use the note from @tony-johnson 

https://gist.github.com/tony-johnson/a88e896fda979d33bf2d

if possible.

**Comment by attipaci** [comment]
I started with Tony's code above, fixed it  up (since it was broken) and simplified it further. I plan to include it in the 1.17.0 release...
