### ISSUE TITLE
data segments greater than 2GB

### ISSUE THREAD

**Issue by jburke-cadc** [nom-tam-fits/nom-tam-fits#54]
We are starting to process fits files that have data segments greater than 2GB. Reading the fits file, getting the Header, and calling getDataSize returns a negative value less than 2GB. getDataSize returns a long but possibly an int is used somewhere in the calculation and it's wrapping?

An example header from one of the files:

SIMPLE  =  T
BITPIX  =  -32
NAXIS   =  2
NAXIS1  =  23826
NAXIS2  =  23543
EXTEND  =  T

returns a data size of -2051228048.

Thanks
Jeff

**Comment by ritchieGitHub** [comment]
The problem here is probably that >2Gb files are untested. We have prepared for it in part but not jet fully. I will take a look this weekend for some tests. Can you provide a test file?

**Comment by jburke-cadc** [comment]
Here's a link to 2.2GB fits file.

http://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/data/pub/CFHTSG/G021.006.921%2B30.145.R.fits

Had a quick look through the Header class. Looks like trueDataSize method needs to use a long instead of an int to calculate the segment size. All other downstream methods look like they are using long. If I can get a publicly available git repo I will patch and ask for a pull.

**Comment by jburke-cadc** [comment]
Should mention that is a simple fits file, only one extension.

**Comment by ritchieGitHub** [comment]
a pull request would be great! I have time to look at the problem this weekend.

**Comment by ritchieGitHub** [comment]
thanks for the fix, I just added a unit test and files with a hdu as big as 10 GB could be read (with enough memory ;-) One of the future version will be able to handle the data with memory mapped files so memory will be no bottleneck anymore.
