### ISSUE TITLE
Compression of variable-length arrays (VLAs) in binary tables

### ISSUE THREAD

**Issue by attipaci** [nom-tam-fits/nom-tam-fits#557]
We don't currently implement the compression of VLAs in binary tables according to specification. While we compress the heap pointers, we leave the heap data uncompressed. But that is not the standard that we are supposed to follow. Instead the FITS standard 4.0 describes ah method of compression both the heap, and the pointers (64-bit Q-type pointers for the compressed heap, and P or Q-type pointers for the uncompressed heap).

We therefore should implement the compression of VLAs to provide more complete support of binary table compression.

__UPDATE__:

As it turns out the VLA compression implemented by CFITSIO and its `fpack` does not actually follow the FITS 4.0 standard (or the original Pence+2013) convention. It is likely, that the maintainers of the standard and CFITSIO will choose to update the standard to match the actual behavior. For this reason, we shall provide VLA compression that is CFITSIO compatible by default. However, because there is a chance that one may need to read compressed VLAs produced by other tools, which actually followed the original prescription, we also provide `CompressedTableHDU.useOldStandardVLAIndexing(boolean)` to allow selecting the convention to use for decompressing tables with VLA columns.

**Comment by attipaci** [comment]
This is actually a pretty nasty thing to fix. All the binary table compression was implemented to work not on the `BinaryTable` data but on the regular 2D `ColumnTable` element of it. As such the compression has no sense of the heap whatsoever, and therefore cannot possibly operate on the heap of the (unknown) encompassing `BinaryTable`.

I can think of two ways to 'fix' this:

 1. The clean way is to reimplement the compression classes to work with `BinaryTable` instead of the dumb `ColumnTable` component. This would keep the API simpler, and similar, but would break backwards compatibility on functions that likelyno-one ever used. (These functions should not have been exposed to users in the first place!)

 2. Keep API compatibility, and add work around by adding a bunch of bolt-on functions, which must be used together to allow the table compression classes to access the heap data.

I'm debating which is the less bad way to proceed from this whole that was dug when compression was added in this form....

**Comment by attipaci** [comment]
Hi @keastrid,

I think I'm well on the way to sorting out the binary table compression issues. I have now modified the table tile compression/decompression classes to add a proper procedure for compressing/decompressing variable-sized columns. I have verified that this works more or less how it is is described in the FITS standard. I have checked the storage of compressed table entries the compression/decompression of the compressed and original heap pointers, and the recovery of the original data through them.

I am now getting a lot of errors from the unit testing though. I suspect this is the fault of the unit tests having been poorly designed -- more to confirm the old (bad) behavior, rather then verifying the proper behavior. I'll have to dive in a little more to see exactly why each test fails and consequently adjust the test or else fix the newly added code. I think it will take a week or two. But, when it's all done, I'll create a PR with the changes, and you can check it out to see if this resolves any of the issues you have been experiencing...

After that, I'll have to make sure I add sufficient unit test coverage for all the new code. So, My guess is that will delay 1.19.1 by a couple of weeks. But it's all for a good cause if the fixes do stick.

**Comment by keastrid** [comment]
Sounds good!

I'll give it a test when it's PRed, thanks!

If it's available on the system, it would probably be good to incorporate fpack and funpack into some unit tests, or add base files to compare against that have been run through them.

**Comment by attipaci** [comment]
I finally found the discrepancy between `fpack` and the newly implemented VLA compression by us. And the issue seems to be in fpack. Specifically on p.50 of the FITS 4.0 specification, it has the following prescriprion for storing the VLA array descriptors in the compressed table:

> Append the VLA descriptors from the uncompressed table (which may be either Q-type or P-type) to the temporary array of VLA descriptors for the compressed table.

So However, fpack clearly does the opposite. It starts with the Q or P type uncompressed descritors, and appends the compressed descriptors after. If I swap the order from the prescription, everything it works great...

So, the question is, should we be standard compliant, or fpack compliant. I think the former...

I'll submit a bug report to fpack, but I'm not sure what they will do given how they have been producing the wrong compressed table format for who knows how long...

**Comment by keastrid** [comment]
That is odd, it'd be interesting to see what they say.

How complicated would it be to add an option to control where they get added? Over in AIJ we're planning to allow saving of measurements tables (for light curves) as fits tables, and as they get shared and archived they need to be consumable by other programs, and we would like to enable compression by default for them as (if I'm reading the spec right) it is always lossless and has significant file size reduction.

Is it possible to detect when a column has them placed in the wrong order, so that `nom.tam` can at least read the tables?

**Comment by attipaci** [comment]
Well, I can think of different ways of approaching this.. I'll probably digest it more before rushing into action. But, what came to my mind so far are:

- implement the documented way, and ignore the fact that is incompatible with `fpack` / `funpack`.
- implement the `fpack` way, and ignore the fact that this deviates from the standard.
- add an option to process table compression / decompression with the reversed descriptor order used by `fpack`.
- We could possibly 'detect' the wrong order, as the resulting pointers (or at least some of them) will be all over the place, and way outside of the heap. But it's not foolproof, especially on large heaps. But if we find that there are compressed descriptors that point outside of the heap area, we could try the reverse order automatically. That of course adds a fair bit of complexity (and hence more chance for bugs, and more tedium on writing tests to cover).

And if and when Bill Pence confirms my diagnosis on `fpack` / `funpack`, I could anticipate one of the following reactions from him:

  - change `fpack` / `funpack` to match the FITS standard and the original convention by Pence+2013. (One could imagine adding an option flag to `funpack` to allow unpacking tables compressed with the wrong order)
  - change the FITS standard, and update the Pence+2013 to match what fpack actually does.
  - do nothing about either.

Based on what Bill Pence says / does, it may be clearer to us what is the best way to proceed.

**Comment by attipaci** [comment]
Hi @keastrid,

Just an update. Still working on the VLA compression. I have found further bugs in `fpack` whereby it's handling the `PCOUNT` and `THEAP` keywords wrong when compressing the tables (not to mention that it does not use the compression algorithm that is selected by the command-line option). The problem is quite obvious in fact. It seems like,

1. It keeps the `THEAP` value of the original table, whereas it should save the original as `ZTHEAP` and write its own `THEAP` value.
2. It does use original heap offset (apparently) but the `PCOUNT` value it writes is the heap size, not accounting for the offset (either its own or the original). This is quite obvious. For example, in my test case, the heap descriptor of the compressed table is 685 bytes at offset 1637. That is the data ends at heap offset 2322. But `PCOUNT` is 2322, whereas it should be 2322 + 16 (if the heap was immediately after the main table containing single Q-type descriptor), or else 2322 + 1024 (if the THEAP value is to be believed -- which turns out to be correct).

If I correct the incorrectly stored `PCOUNT` (and swap the order of indices as mentioned above), I can read the `fpack`-ed table correctly. In any case, it is quite clear that `fpack` and `funpack` have some serious issues. I don't think they make a good reference implementation for us. As far as I can tell nobody should use `fpack` with VLA data unless they want to end up with totally unreadable / non-standard crap.

**Comment by attipaci** [comment]
@keastrid, Another day, another update. I heard back from the maintainers of CFITSIO. They are looking into this. They also expressed their preference for keeping the CFITSIO behavior as is, and instead changing the documentation to match.

**Comment by attipaci** [comment]
@keastrid,

PR #568 is now ready for you to look at. Now table compression is `fpack` compatible (notwithstanding the fact that `fpack` does not handle `THEAP` keywords right, but I expect they will fix that soon).

Please give it a try to see if there are lingering issues still. I'll be adding unit tests to make sure that all new code is covered.

**Comment by keastrid** [comment]
@attipaci 

Thanks! I'll have a look at it this week.

**Comment by attipaci** [comment]
This already includes #552 (which has been merged to master).

**Comment by attipaci** [comment]
@keastrid,

I keep finding more bad bugs with `fpack`, as I was trying to add cross-testing. It turns out that for VLA columns, `fpack` sets `ZCTYPn` always to `GZIP_1` for `byte[]` type VLAs, `GZIP_2` for `short[]` type VLAs, and `RICE_1` for `int[]` type VLAs. At the same time it in fact uses `NOCOMPRESS` for the `byte[]` and `short[]` columns, but does indeed use `RICE_1` for the `int[]`. This is regardless of what compression option (`-g`, -`g2`, or `-r`) is used on the command line.

As a result, `fpack` messes up antthing except `int[]` type VLAs. Therefore, I cannot really check against it in the tests, at least not until the (C)FITSIO folks fix this.
