### ISSUE TITLE
Is it necessary to close Fits object?

### ISSUE THREAD

**Issue by supermartzin** [nom-tam-fits/nom-tam-fits#56]
Hi,

just want to be sure. I noticed that `Fits` class implements interface `Closeable`. Is it necessary to explicitly call the `close()` method when created object with `Fits fits = new Fits(file)` for proper resources release?

Thanks!

**Comment by ritchieGitHub** [comment]
yes, else you will leave file pointers open. Not in all cases the closeing is really nessesary but in case of a uncompressed file it is mandatory. Bether always close the fits file.
