### ISSUE TITLE
Allow RICE_1 and HCompress with defaults (also Rice for tables)

### ISSUE THREAD

**Issue by attipaci** [nom-tam-fits/nom-tam-fits#563]
Our constructors for Rice / HCompress compressors require a non-null option argument, which in practice means that users must supply options explicitly when using the algorithm to compress. However, FITS defines default values for the options, so we should allow using `RICE_1` or HCompress without providing them options explicitly. This is also necessary to enable table compression with `RICE_1`, which we currently do not support for this very reason.

In practice that means that currently only the optionless `GZIP_1`, `GZIP_2` algorithms can be used for tables.

On a related note, we do allow other 'optionless' algorithms on tables, such as the lossy PLIO, which is not allowed for tables as per FITS 4.0. So, we should also check and throw an appropriate exception is someone tries to compress binary tables with an unapproved algorithm.

**Comment by keastrid** [comment]
I'm not sure all of these are possible currently, as per the FITS 4.0 spec, p. 49:

> The permitted algorithms for compressing BINTABLE columns
are ’RICE 1’, ’GZIP 1’, and ’GZIP 2’ (plus ’NOCOMPRESS’),
which are lossless and are described in Sect. 10.4. Lossy compression could be allowed in the future once a process is defined
to preserve the details of the compression.

**Comment by attipaci** [comment]
OK, but currently we do not allow `RICE_1` from that list for the reasons mentioned above. So the issue is valid. And maybe more so, because I don't think we have anything preventing us from using the lossy `PLIO` at the same time...

**Comment by attipaci** [comment]
I'll change the ticket description somewhat...

**Comment by keastrid** [comment]
Yes, the issue is still valid. 

The compression options should definitely be limited to what is actually available for tables.

**Comment by attipaci** [comment]
OK, in the PR in prep, `RICE_1` now works with 8 -- 32-bit integers (the standard allows for 64-bit also, but there is currently no algorithm anywhere I know of that supports it -- cfitsio certainly does not).

And `CompressedTableHDU.fromBinaryTable()` will throw an `IllegalArgumentException` if supplied with an algorithm that is not suitable for table compression...
