### ISSUE TITLE
Writing a Fits Object to an external Stream should propogate exceptions so clients can take action/inform.

### ISSUE THREAD

**Issue by JonCook** [nom-tam-fits/nom-tam-fits#59]
This problem manifests itself on an NFS mounted file system when writing a Fits File that causes the user to exceed their disk quota.

It seems that the problem is located in nom.tam.fits.Fits.write(DataOutput) at:
```java
...
if (newOS) {
    try {
        obs.flush(); //<----------exception raised here
        obs.close(); 
    } catch (IOException e) {
        LOG.log(Level.WARNING, "Warning: error flushing/closing FITS output stream", e);
    }
}
...
```
At this point, the file is dumped and nom.tam.fits is ready to flush and close the stream (NFS has a cache, so the data is not saved to disk really).The problem appears when calling the 'flush' method, because the remaining data is dumped (from the NFS cache) but there is not enough space (because of the disk quota). The catch statement shows the warning message, but no exception is raised. There is a real problem here because the file is not totally dumped, so it is a real error but it seems that the file was saved successfully to a user. Only later, when a user inspects the file, an error is found. An exception should be raised here.

For example the Log.log could be replaced with:
```java
throw new FitsException("Error closing FITS output stream: "+e);
```

**Comment by JonCook** [comment]
I am happy to provide a pull request for this if it helps? Thanks.

**Comment by ritchieGitHub** [comment]
That alway helps😄
thanks for the report!

**Comment by ritchieGitHub** [comment]
the exception is now propagated as a FitsException. the snapshot version now includes this feature

**Comment by JonCook** [comment]
Thanks for doing this. Sorry I was too slow with my PR. ;-)

**Comment by ritchieGitHub** [comment]
no problem thanks for helping, I just included the code you wrote ;-)
