### ISSUE TITLE
include a zip in the build that can be used to deploy the old structure

### ISSUE THREAD

**Issue by ritchieGitHub** [nom-tam-fits/nom-tam-fits#6]
- that includes an expanded javadoc
- names of the jars 
- include the test sources
- latest release note file
- pdf of the documentation?

**Comment by ritchieGitHub** [comment]
@TomMcGlynn  please check if the zip is ok for your use, I did not split the note strings to 80 chars yet, that will be for the next release. also the pdf is not generated (nothing changed anyway?) we can generate the pdf in the next realease.

**Comment by TomMcGlynn** [comment]
Just went tried to go through everything and it looks great.  I especially like the care with which the src jar was created including the header data which I don't think had been there before...

The only thing that was problematic was understanding where to find things.  I think I was expecting there to be a special Maven target that would build the zip but eventually realized that it was in the standard 'package' target.   I think this fully addresses the need and I'll be installing the new version as soon as I close this.

**Comment by ritchieGitHub** [comment]
wait it is no released version yet ;-) just an test snapshot, as soon you fill in the src/changes/changes.xml with the "beautifull" release notes. i will create a real release that also will enter the central repo.
