### ISSUE TITLE
Request to read header data more efficiently.

### ISSUE THREAD

**Issue by JonCook** [nom-tam-fits/nom-tam-fits#62]
Given the attached FITS File (I can't attach it, its too big?) and output from a simple test utility the memory consumption seems to be quite high when we have FITS files with 100mb+ headers. 
See "At: after read" metrics below.
```
At: start
      Total Memory:  121856
      Maximum Memory:1805824
      Free Memory:   121210
      Used Memory:   645
At: before read
      Total Memory:  121856
      Maximum Memory:1805824
      Free Memory:   121210
      Used Memory:   645
At: after read
     Total Memory: 914432
     Maximum Memory:1805824
     Free Memory:   186116
     Used Memory:   728315
At: after gc
      Total Memory:  877056
      Maximum Memory:1805824
      Free Memory:   327370
      Used Memory:   549685
At: after data read1
      Total Memory:  877056
      Maximum Memory:1805824
      Free Memory:   327370
      Used Memory:   549685
```
The structure is quite different to some FITS files. We have 31936 Binary Tables, all with the same structure but with a varying number of rows in each table ranging from 11 up to 1103 I think.

I had a look and it seems the majority of the time when calling the  read method is spent in the constructor of HeaderCard.java which is doing quite a lot of String manipulation, substring, trim, replace etc. Could this be allocating lots and lots of string objects which is taking up the memory?

Snippet from a conversation with @TomMcGlynn:
_To get a sense of how many bytes we might expect that to take up we can just do (and we get 307 MB):_
```
31,000x65x80 x 2 (since Java char's are 2 bytes)
```
_That's about half of the memory usage we are seeing.  However, while there is a fair bit of coding to attempt to be efficient with memory usage in the data side, I don't recall doing much of anything to be efficient with the header data, so a factor of two isn't too surprising.  This also may explain why you are seeing differences in the more recent versions.  Some of the release notes do refer to 
changes in Header.java and I could imagine this affecting the code._

_This is a useful example and I hope that I can work to find where the memory is getting used up. There's likely easy changes that will significantly cut memory usage (a factor or two or so), but some more significant changes (e.g., maybe a new PhantomHDU class that just notes the HDU size and offset), it's still going to require >100MB to read the file._

Then later with @ritchieGitHub;
_The solution must be not to load all header cards at the same time altogether._

_For the data I already have an idea how to get it out of the java memory. But here we are taking about headers..._

_I think the solution must be to read them block for block (2880), Introducing the header-"block" as knowlage would solve some other side requirements. But problems will be introduced in areas like validating and sorting the header cards. I think the best solution would be to have a defined number of cards in memory (like the first, the last and a number (10?) in a kind of ruler that shifts over the header-data on demand. An index could be created in a temporary file to speedup the
searching._

Finally I also have some doubts about this code which seems to read the whole HDU block into memory: Currently there is come code although changed slightly in the latest version:
```java
public BasicHDU readHDU() throws FitsException, IOException {
        ...
        //dataStr already defined: it is the data input
        ...
        Header hdr = Header.readHeader(dataStr);
        ...
        Data datum = hdr.makeData();   //<---- this creates the space for the entire data
        try {
            datum.read(dataStr);       //<---- this loads the entire data
        } catch (PaddingException e) {
            e.updateHeader(hdr);
            throw e;
        }
```

Any help or guidance would be much appreciated.
Thanks

**Comment by ritchieGitHub** [comment]
first thanks for your report ;-)
it would be great to have such a big file. Can you give me a donwload link? or put it on a online disk like bitcasa?

**Comment by JonCook** [comment]
I made the said file available via wetransfer. Hope you received it. Thanks!

**Comment by ritchieGitHub** [comment]
it is included as a unit test nom.tam.fits.test.TestFitsFileWithVeryBigHeaders.testFileWithVeryBigHeaders()
(still without asserts)

**Comment by ritchieGitHub** [comment]
I have done some tests and could profile the memory usage a little, and increase the performance as well (15%). My idea to read only parts won't help much because of the many relatively small hdu's. My calculations give 39Mb memory usage for one hdu 
```
  try (Fits f = new Fits(BlackBoxImages.getBlackBoxImage("OEP.fits"))) {
            BasicHDU<?> hdu;
            while ((hdu = f.readHDU()) != null) {
                hdu.getHeader();
            }
        }
```
and the memory is not filling up, everything was cleaned up correctly.

Could you please redo your test with the current snapshot? As you will see in the profiling the cpu time is used up using parsing but not with making garbage. This part was changed very deeply in the last 2 versions, there should be almost no trimming left.

**Comment by ritchieGitHub** [comment]
some additional test show that 22Mb is used by the test and library and other stuff so the memory used for 1 hdu of this file comes to ~17Mb, that not to much or?

**Comment by JonCook** [comment]
Sounds good. Thanks very much for looking into this. We are using quite an old version 1.06 so I will try with the latest snapshot. Thanks again.

**Comment by ritchieGitHub** [comment]
found another 20% performance improvement by following a recommendation of http://www.perlmonks.org/?node_id=607740 where they remove the backtracking from the regular expression. This improved the expression speed drastically, in our case the hdu reading improved to 1650ms from 2100ms before changing the regular expression. Overall this issue was a great improvement we came from 2900ms down to 1650ms so almost double speed ;-)

@JonCook attention to set the logging options, because the file triggers a lot of warnings (duplicate header keys), we use java.util.logging as a logging framework. you can find the snapshot:
```
<repositories>
    <repository>
        <id>sonatype-snapshots</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>    
```
or if you do not use maven from: https://oss.sonatype.org/content/repositories/snapshots/gov/nasa/gsfc/heasarc/nom-tam-fits/1.14.0-SNAPSHOT/ (the build time is included in the name)

**Comment by ritchieGitHub** [comment]
I will leave this issue open till the next release (1 to 2 weeks) so you can add your findings, and we may improve even more.
