### ISSUE TITLE
Compressed tables lose column names

### ISSUE THREAD

**Issue by keastrid** [nom-tam-fits/nom-tam-fits#636]
Just updated to 1.20 (we had previously just pulled in the compression fix), and we found an issue when compressing tables - they lose the column names and take on the new default column names

This code is enough to reproduce it:
```java
var fits = new Fits();
var table = new BinaryTable();
table.addColumn(new double[]{1, 2, 3, 4});
var h = table.toHDU();
h.setColumnName(0, "test", "test");
var compressedHdu = CompressedTableHDU.fromBinaryTableHDU(h, -1);
compressedHdu.compress();
h = compressedHdu;
fits.addHDU(h);
fits.write(Path.of("test.fits").toFile());
fits.close();
```

Commenting out `h = compressedHdu;` produces a table with the correct headings.

**Comment by attipaci** [comment]
Ouch! It's too bad you did not catch this in the weeks (months) before the final release. I'll look into finding a fix for it...

**Comment by keastrid** [comment]
Sorry, it was on my todo then other things happened. Though I'm not sure I would've caught it quickly.

**Comment by attipaci** [comment]
No worries... :-D
