### ISSUE TITLE
extended the card builder with order functions

### ISSUE THREAD

**Issue by ritchieGitHub** [nom-tam-fits/nom-tam-fits#65]
To have more control over the oder of cards the card builder can be extended with functions like:

```
.before(header).card(header2).value(xxxx)...
.after(header).card(header2).value(xxxx)...
.card(header).remove()...
.card(header).till(header).moveAfter(header)..
.select("Z[A-Z0-9]*").together().moveBefore(END).. // select with regex
```

And a lot more like these where the behavior should be logical an good documented what happens when a card does not exist.

**Comment by JonCook** [comment]
This is a nice idea. I wonder if it could be further extended to include ordered keywords with groups and categories as this is almost a mandatory requirement for most applications. We have out own implementation of this whereby a default list of categories and keywords are provided but it is possible for the user to override this behaviour with their own provided.
