### ISSUE TITLE
readHeaderSkipHDU functionality

### ISSUE THREAD

**Issue by ritchieGitHub** [nom-tam-fits/nom-tam-fits#66]
after already mutilple requests for a skip data funcion, it should be implemented in the core library:

```
try (Fits f = new Fits("target/testSomeBlanksInCompressedFloatImage.fits.fz")) {
            Header header = f.readHeaderSkipHDU();
            header.card("SOMETHING").value("A VALUE");
            ......
            header.rewrite();
}
```

this header shoudl be rewriteable! so the header can be changed with minimal overhead.

**Comment by attipaci** [comment]
Well, in essense `Fits.readHDU()` does that already. The header is only rewritable in random access mode, in which case `readHDU()` skips over the data by default (deferred read). So, the following code, which is nearly identical to the one proposed, readily performs what is described in this ticket:


```java
try (Fits f = new Fits("target/testSomeBlanksInCompressedFloatImage.fits.fz")) {
    Header header = f.readHDU().getHeader();
    header.card("SOMETHING").value("A VALUE");
    ......
    header.rewrite();
}
```

As such, I think this issue can be closed.
