### ISSUE TITLE
Multiple CONTINUE keywords not permitted

### ISSUE THREAD

**Issue by JonCook** [nom-tam-fits/nom-tam-fits#69]
Hi,

In the process of trying to upgrade from 1.06 to the latest snapshot nom-tam-nom-tam-fits-1.14.0-20160111.054820-131.jar I have encountered what seems to be a problem writing multiple CONTINUE keywords. They should work I believe as part of the CONTINUE Long String keyword Convention, see example here: http://fits.gsfc.nasa.gov/registry/continue_keyword.html

Take the following code example (it is a very simple example only to demonstrate the problem):

```java
    private static final String COMMENT_SEP     = " / ";
    
    private static void writeContinueTest() throws FitsException, IOException {
        float[][] data = new float[500][500];
        try (Fits f = new Fits()) {
            BasicHDU<?> hdu = FitsFactory.hduFactory(data);
            hdu.getHeader().addValue("DESC    ", "product description a bit large just to see if it can be translated&", "");
            hdu.getHeader().addValue("CONTINUE", " properly (and read procedure also)&", "");
            hdu.getHeader().insertCommentStyle("CONTINUE", "  ''" + COMMENT_SEP + "&");
            hdu.getHeader().insertComment("Name of this product");
            f.addHDU(hdu);
            try (BufferedFile bf = new BufferedFile("testMultipleContinueInput.fits", "rw")) {
                f.write(bf);
            }
        }
    }
```

Results in:
```
...
DESC    = 'product description a bit large just to see if it can be translated&'
CONTINUE  '' / &
COMMENT Name of this product
...
```

It should be as per older versions of the library:
```
...
DESC    = 'product description a bit large just to see if it can be translated&'
CONTINUE  ' properly (and read procedure also)&'                                
CONTINUE  '' / &
COMMENT Name of this product
...

Thanks for any help.
Jon

**Comment by ritchieGitHub** [comment]
This should not be done by hand! This is done automatically if the string is to long and long-string enabled. You should adapt the code let the library handle long-strings, ok?

**Comment by JonCook** [comment]
I tried using the library for example with:
```java
hdu.getHeader()
                .addValue(
                        "DESC",
                        "product description a bit large here we go once upon a time there was a big bear in the high up there in the sky mountains just to see if it can be translated properly (and read procedure also)",
                        "Name of this product");
```

This gave me:
```
DESC    = 'product description a bit large here we go once upon a time there w&'
CONTINUE  'as a big bear in the high up there in the sky mountains just to see&'
CONTINUE  ' if it can be translated properly (&' / Name of this product         
CONTINUE  'and read procedure also)' 
```
Which doesn't seem correct? Isn't the comment in the wrong place? I will investigate updating our code to use the built in functionality of the library but currently we have our own implementation.

**Comment by ritchieGitHub** [comment]
No the comment is allowed everywhere, by spreading the comment over multiple lines more comment characters are allowed.

**Comment by ritchieGitHub** [comment]
It would be very hard to allow the "old" behavior in the library. So it would be good if you can use the buildin longstrings

**Comment by JonCook** [comment]
To me, this doesn't look like a proper implementation of the Long String convention although apparently it is a valid FITS file.

```
DESC    = 'product description a bit large just to see if it can be translated&'
CONTINUE  ' properly (and read procedure also)&'                                
CONTINUE  '' / &
COMMENT Name of this product
```

**Comment by ritchieGitHub** [comment]
That not a header generated by nom-tam-fits, or? It is legal but a little strange.

**Comment by JonCook** [comment]
No its a header our software generates but now it is not possible to generate this I think with the current library?

**Comment by ritchieGitHub** [comment]
No, not easily. If you really want that, I can take a look this weekend if there is a back door.

**Comment by JonCook** [comment]
That would be great if you have time just to know. Also It seems long comments get truncated?

```java
        hdu.getHeader()
                .addValue(
                        "DESC",
                        "product description a bit large here we go once upon a time there was a big bear in the high up there in the sky mountains just to see if it can be translated properly (and read procedure also)",
                        "Lets make a really really erally long comment string as well to see what happens witht he blirary I am really not sure");
```

```
DESC    = 'product description a bit large here we go once upon a time there w&'
CONTINUE  'as a big bear in the high up there in the sky mountains just to see&'
CONTINUE  ' if it can be translated properly (&' / Lets make a really really era
CONTINUE  'and read procedure also)' / lly long comment string as well to see wh
```

**Comment by ritchieGitHub** [comment]
That is something we want to fix by adding
```
CONTINUE  '&' / more comments 
```
For now we have a maximum comment length of ~80 chars, as with all other comments. The space available will be needed if there is not annough the comment will be trimmed to fit.

**Comment by JonCook** [comment]
I've actually managed to recreate the functionality I require. Thanks. I will leave this for a little bit longer and then close if ok?

**Comment by ritchieGitHub** [comment]
Yes, but the requirements you need to meet would interest us! It could be of use for others?

**Comment by ritchieGitHub** [comment]
For example why does it have to be formated the way you wrote? Is there a "compromize" between the way we do it and the way you need it? (ported this in the wong issue)
