### ISSUE TITLE
Option for inserting HeaderCard to a specific index

### ISSUE THREAD

**Issue by supermartzin** [nom-tam-fits/nom-tam-fits#7]
Hi!

Is there any option in your library how to insert a new **HeaderCard** to a *specific index* in **Header**?
For example, I have 10 HeaderCards in Header and I want insert new card to index 5 so first 4 cards will be the original ones, 5th one will be my inserted and the rest 5 cards will be moved in position by 1 place.

Thanks in advance.

**Comment by ritchieGitHub** [comment]
Hi,

yes, you can do that with the header iterator. A small example:
```java
Header hdr = hdu.getHeader();
Cursor<String, HeaderCard> iterator = hdr.iterator();
for (int index = 1; index < 5; index++) {
    iterator.next();
}
iterator.add(CRVAL1.key(), new HeaderCard(CRVAL1.key(), 0., "Longitude at reference"));
```
But i see that it would help if there was a posibility to move the iterator to a position, we will create such a possibility in  the next version.

Thanks for helping improving the api

**Comment by ritchieGitHub** [comment]
just a note in the new api this can be done a little bit simpler:
```java
hdr.iterator(4).add(CRVAL1.card().value("xx"));
```
a release date is not jet scheduled we are discussing the new api at the moment.

**Comment by supermartzin** [comment]
Thanks, adding to index works smoothly but I encountered an error when trying to remove a ```HeaderCard``` from specific index.
This is header of my sample FITS file:
```
Image #1
    SIMPLE  =                    T
    BITPIX  =                   16
    NAXIS   =                    2
    NAXIS1  =                 1530
    NAXIS2  =                 1020
    KEY_WORD= 'value   '           / comment of FITS header card
    EXPOSURE=  0.14000000000000000
    TEMPERAT= -14.8000000000000000
    DATE-OBS= '2012-04-20T16:16:12.1' /     UT
    JD      =  2456038.17791800000
    DATE-LOC= '2012-04-20T18:16:12.1' /     LT
    FILTER  = 'V-photom 1.00'
    XPIXSZ  =                  9.0
    YPIXSZ  =                  9.0
    AVISUMIN=                102.0
    AVISUMAX=                130.0
    AVISUTYP=                  0.0
```
I added card ```KEY_WORD``` with iterator to position **6** (*index 5*) and with the same piece of code I tried to remove that card from header. So I changed ```iterator.add();``` to ```iterator.remove();```  and during saving the file it throws following exception:
```ex
nom.tam.fits.FitsException: Key NAXIS2 not found where expected.Found KEY_WORD
	at nom.tam.fits.Header.cardCheck(Header.java:1535)
	at nom.tam.fits.Header.checkBeginning(Header.java:1510)
	at nom.tam.fits.Header.write(Header.java:932)
	at nom.tam.fits.BasicHDU.write(BasicHDU.java:227)
	at nom.tam.fits.Fits.write(Fits.java:911)
	at cz.muni.fi.fits.engine.NomTamFitsEditingEngine.addNewRecord(NomTamFitsEditingEngine.java:52)
```

I noticed with debugging that in header collection of cards it removed card ```NAXIS2``` instead of ```KEY_WORD```, which was still there.

Do you have any idea what can cause this problem?
Thanks :)

**Comment by ritchieGitHub** [comment]
just a blind geass because i do not have the code available just now. i thing the remove removes the current and add adds after the current, just make one iteration more.

**Comment by supermartzin** [comment]
Thanks for advice, I finally found it out. 
Actually **remove** operation removes the item on previous position (cursor pointing to index 3 - removes item with index 2) and the **add** operation adds the item on current position (cursor pointing to index 3 - adds to index 3). Note: index starting from **0**.

I also noticed that there are some required keywords that must be in each fits header that's why I got that ```FitsException```.

**Comment by supermartzin** [comment]
Another remark. I would expect that this piece of code
```java
Fits fits = new Fits(fitsFile);
Header header = fits.getHDU(0).getHeader();
HeaderCard card = new HeaderCard("KEYWORD", "value", "comment of FITS header card");
header.addLine(card);
```
will add new card with key `KEYWORD` at the end of the header but instead it puts this card after all mandatory keys, for example on position **5** (starting with 0):
```
Image #1
    SIMPLE  =                    T
    BITPIX  =                   16
    NAXIS   =                    2
    NAXIS1  =                 1530
    NAXIS2  =                 1020
    KEYWORD = 'value   '           / comment of FITS header card
    TEMPERAT= -14.8000000000000000
    DATE-OBS= '2012-04-20T16:16:12.1' /          UT
    JD      =  2456038.17791800000
    FILTER  = 'V-photom 1.00'
    XPIXSZ  =                  9.0
    YPIXSZ  =                  9.0
    AVISUMIN=                102.0
    AVISUMAX=                130.0
    AVISUTYP=                  0.0
```
I think it would be nice to add all new keywords at the end of header, not somewhere inside. Now I can achieve this behaviour only by using iterator with iterating to the end.
Thanks :)

**Comment by ritchieGitHub** [comment]
I think you are right we should include some more  positioning helper methods, like "lastCard" "firstCard". For version 2.0.0 I could also imaging to rename all the unspecific "add"/"remove" like methods and name them more specific like "addAfterCurrent" and "removeCurrent". For  version 1.X.X this would be a to big change, but for 2.0.0 that would be ok. @TomMcGlynn  what do you think?

**Comment by TomMcGlynn** [comment]
The positioning of cards within the header is a fraught topic.  Generally I don't think it's very useful to put cards at specific numerical locations within the header.  As noted above the first few header cards are mandatory and must be in a specific order.  After these there are no semantics associated with the order of cards with the sole exception of the deprecated BLOCKED keyword which must appear in the first 36 records.  I think it may be unwise to facilitate structuring of the header by card number.  What I think is appropriate is to provide facilities to ensure that headers are appropriately organized (where the user may decide what is appropriate).  I.e.,
should the header order for a table be TFORM1, TFORM2, ... TTYPE1, TTYPE2, TUNIT1, TUNIT, ...
or TFORM1, TTYPE1, TUNIT1, TFORM2, ....  The ability to move the cursor to a given keyword
helps here.

What is the use case where you want to be able to put cards in specific locations in the header (as opposed to locations relative to other header keywords)?  

With regard to starting at the beginning or at the end...  One reason to choose the former is that
it's easy to find the end, but it's harder to know the first location at which it is valid to write an arbitrary header card.   However I don't have any strong preference here.  I would think one could
use the cursor to find the END keyword and insert before there...

**Comment by supermartzin** [comment]
I am making an application that is supposed to be able to edit header of FITS files in batches and this is one of the specification I need to implement - that is user will be able to insert a new card to specified position.
But as you are saying that there are some rules in header cards order, I will consult this functionality with my supervisor.

**Comment by TomMcGlynn** [comment]
Martin Vrábel wrote:
>
> I am making an application that is supposed to be able to edit header 
> of FITS files in batches and this is one of the specification I need 
> to implement - that is user will be able to insert a new card to 
> specified position.
> But as you are saying that there are some rules in header cards order, 
> I will consult this functionality with my supervisor.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nom-tam-fits/nom-tam-fits/issues/7#issuecomment-91002235>.
>
If by 'a specified position' you mean at the earliest/latest possible 
position or immediately before or after an existing card, then I think 
you've got that.    I've never had occasion to need to insert a card at 
the N'th location independent of the location of other keywords.  I'm 
not sure I'd want to encourage that kind of design. It is in any case 
easy to emulate with a cursor.

     Tom

     Tom

**Comment by supermartzin** [comment]
Anyway I think at least newly added header card should be inserted at the end by default, not somewhere in the middle of header.

**Comment by ritchieGitHub** [comment]
in the 1.12.1 snapshot there ar some new position helper methods. like:

header.iterator(index) -> start the iterator an position to that index.
iterator.end() -> position the iterator to the last header card.
iterator.next(count) -> execute the next method count times (return the last).

that should make your live easier and sill keep backward compatibility.

```xml
	<dependencies>
		<dependency>
			<groupId>gov.nasa.gsfc.heasarc</groupId>
			<artifactId>nom-tam-fits</artifactId>
			<version>1.12.1-SNAPSHOT</version>
		</dependency>
	</dependencies>
	<repositories>
		<repository>
			<id>sonatype-snapshots</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>  
```

**Comment by supermartzin** [comment]
Thanks, I'm going to try it right away.

**Comment by supermartzin** [comment]
So I tried these new methods, but they don't work like expected.
First I used
```java
header.iterator().end();  // move cursor to the end
header.iterator().add(...);  // insert new header card
```
but it added the new card at first available position after mandatory keywords (in my case on **6th** position instead of 18th - first 5 cards contains mandatory keywords).
So I tried another trick, I used parametrized method ```next()``` like this:
```java
header.iterator().next(header.getNumberOfCards());  // move cursor to the end
header.iterator().add(...);  // insert new header card
```
but it ended with the same result :/

**Comment by supermartzin** [comment]
Okay, my fault, I'm using every time the new iterator that's why it doesn't work.
This piece of code works perfectly:
```java
Cursor<String, HeaderCard> iterator = header.iterator();

iterator.end();  // move cursor to the end of header
iterator.add(...);  // insert new card
```
