### ISSUE TITLE
BinaryTable boolean column error

### ISSUE THREAD

**Issue by attipaci** [nom-tam-fits/nom-tam-fits#710]
### Discussed in https://github.com/nom-tam-fits/nom-tam-fits/discussions/708

<div type='discussions-op-text'>

<sup>Originally posted by **johnmurphyastro** December  6, 2024</sup>
Hi @attipaci,
I am looking for sum help creating boolean columns in a BinaryTable. My attempts fail with an exception:

**BinaryTable bt = new BinaryTable();
bt.addColumn(BinaryTable.ColumnDesc.createForScalars(boolean.class));
bt.addRowEntries(true);**

This produces the error:
java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class [Z (java.lang.Boolean and [Z are in module java.base of loader 'bootstrap')
Stack trace:
    nom.tam.fits.BinaryTable.javaToFits1D(BinaryTable.java:3621)
    nom.tam.fits.BinaryTable.addRow(BinaryTable.java:2198)
    nom.tam.fits.TableData.addRowEntries(TableData.java:111)

I am using version 1.20.2
Thanks, John Murphy</div>

**Comment by attipaci** [comment]
@johnmurphyastro, I think PR #709 solves this. Let me know if that works for you or if you find more unexpected behavior....

**Comment by johnmurphyastro** [comment]
Hi @attipaci ,
Great! With that code change, it appears to work
Thanks, John Murphy
