### ISSUE TITLE
design a better Profile picture

### ISSUE THREAD

**Issue by ritchieGitHub** [nom-tam-fits/nom-tam-fits#74]
The current picture was just a fast draft that survived, because we did not find anything more fitting and free. Is there a designer somewhere out there that would like to help and design a nice Profile picture for nom-tam-fits?

**Comment by rmathar** [comment]
One could invent a scrabble-aware picture that looks like pixel data as in https://www2.mpia-hd.mpg.de/~mathar/nomtam.png .
This was created with
```
ft=courier
convert -size 28x32 xc:white -pointsize 11 -font $ft -draw 'text 1,10 fits text 15,20 a text 1,30 nom' -type bilevel nomtam.bmp
convert nomtam.bmp -scale 280x320 nomtam.png
```

**Comment by attipaci** [comment]
I like the idea. Here is after rendering something simple but good looking in inkscape: https://drive.google.com/file/d/1CkRmH5wWuG8p3FvzQGznN8OMAMThLucW/view?usp=sharing

What do you think?

**Comment by rmathar** [comment]
Another idea: a java coffee-cup astronomer's style as in https://www2.mpia-hd.mpg.de/~mathar/nomtam2.svg (and PDF in https://www2.mpia-hd.mpg.de/~mathar/nomtam2.pdf )

**Comment by attipaci** [comment]
I've changed the profile picture for 1.17.0. There is always room for changing it up again in the future...
