### ISSUE TITLE
Possibility to suppress warnings?

### ISSUE THREAD

**Issue by JonCook** [nom-tam-fits/nom-tam-fits#77]
Hi,

Is there a way to suppress this warning:
```
Feb 12, 2016 3:41:41 PM nom.tam.fits.Header addDuplicate
WARNING: Warning: multiple occurrences of key:--------
Feb 12, 2016 3:41:41 PM nom.tam.fits.Header addDuplicate
```

Since upgrading I see it many times for some fits files we have in our system which aren't going to change.

Thanks

**Comment by ritchieGitHub** [comment]
We use the java logging meganim included in core java, so you can just provide a config file to control the logging in detail. See the logging contol file in fits/ src/test/resources as an example

**Comment by JonCook** [comment]
ok. great thanks. We also use this mechanism, so perfect.
