### ISSUE TITLE
NullPointerException when value is too long

### ISSUE THREAD

**Issue by supermartzin** [nom-tam-fits/nom-tam-fits#8]
Hi again,

I came across an issue while I was trying to add new `HeaderCard` to `Header` following data:
```java
HeaderCard card = new HeaderCard("KEYWORD", "random value just for testing purpose - random value just for testing", "");
```
Value has exactly **69** characters.
This card is successfully writen into file in this format:
**KEYWORD = 'random value just for testing purpose - random value just for testing**
(*notice that it has not added ending `'` character)

Next time I read this file and want to write another card in there, it throws `NullPointerException` in `Fits.write()` method.

I was examining this problem and found out that it's caused by incorrectly loaded **KEYWORD** card.
Whole card value is loaded to `HeaderCard` object as **`comment`** and `key` and `value` attributes stays `null`. Then it throws the exception in following part of code in `Header` method `void checkEnd()`:
```java
while(this.iter.hasNext()) {
     HeaderCard card = (HeaderCard)this.iter.next();
     if(!card.isKeyValuePair() && card.getKey().equals("END")) {
         this.iter.remove();
     }
}
```

Wouldn't be possible to add some length checking mechanism to prevent this issue?
Thanks.

**Comment by ritchieGitHub** [comment]
yes, i am just working on the new api and also came over this issue. I will include it as a unit test.

thanks a lot!

**Comment by ritchieGitHub** [comment]
repaired in the review branch (local) with unit test
