### ISSUE TITLE
move to java-8 as a minimum version 

### ISSUE THREAD

**Issue by ritchieGitHub** [nom-tam-fits/nom-tam-fits#81]
Java-8 introduces a lot al features that make the code more readable, simpler and faster. I propose that from version 2.0.0 we move to minimum java version 8 and do a complete cleanup of all the places where java-8 features can help.

@erikfk should we create a own issue per feature or just this master feature for all?

**Comment by attipaci** [comment]
1.15.3 is now expected to be requiring Java 8 -- not because it's required by existing code, but because Java6 is no longer supported, and has know security issues.
