### ISSUE TITLE
update the debian nom-tam-fits library

### ISSUE THREAD

**Issue by ritchieGitHub** [nom-tam-fits/nom-tam-fits#82]
contact the maintainer of the package and discuss an update policy.

**Comment by ritchieGitHub** [comment]
mail send to Florian Rothmaier:

> Hi,
> 
> I see you are the maintainer of the debian package of nom-tam-fits. The package is rather outdated by now.
> 
> https://packages.qa.debian.org/libf/libfits-java.html
> 
> As we are on GidHub now and available in the maven central repository, we want to try to update the debian package. Best method would be to use the artefacts deployed to central:
> 
> https://repo1.maven.org/maven2/gov/nasa/gsfc/heasarc/nom-tam-fits/
> 
> they are signed and readonly and available forever (central repo policy)
> 
> we created an issue for this task:
> 
> https://github.com/nom-tam-fits/nom-tam-fits/issues/82
> 
> if you want to discuss this more openly.
> 
> Ritchie

**Comment by ritchieGitHub** [comment]
send a email to the maintainers list:
```
Hi,

As Florian seems to be unavailable, I redirect my question to the
debian-science-maintainers group.

We would be willing to update the package ourself, but we need some
hints how to do it. And where to register and so on.

As I learned in the mean time, the debain standard enforces the local
build. That is ok with me, the build is a completely standard maven
build, so the packaging should be easy. The release tar's are available
here: https://github.com/nom-tam-fits/nom-tam-fits/releases

Thanks for any help, pointing us to the right starting place.

Ritchie
```

**Comment by ritchieGitHub** [comment]
@attipaci I have got an answer, so we have to
- create a new account at https://alioth.debian.org/
then search for the projects debian-astro and debian-science
- request to join both.
I already did that, @attipaci if you want to manage that you should also join both project. just say in the request that you are also working on the project and we will do it together.

**Comment by ritchieGitHub** [comment]
@attipaci it will be a lot of searching how to do it, do you still want the "job"? If yes:
the maven builder is here:
https://wiki.debian.org/Java/MavenDebianHelper

seems easy, but it is a huge amount of learning involved!

**Comment by attipaci** [comment]
Hi Ritchie,

OK, I put in a request to join debian-science (I was already on 
debian-astro, and have the alioth account)...

In principle, I will be trying to package my astronomical data reduction 
software (crush), which uses the nom.tam.fits libs, for the summer release.

There is a lot of learning to do for sure, but in principle if I manage 
to package crush, I think it should be relatively easy to apply the same 
knowledge to packaging fitslib-java also... My guess is that all will 
depend on just how much time I can devote to the project(s), over the 
next few months. It's not entirely hopeless though...

-- A.

**Comment by ritchieGitHub** [comment]
Good, they answered my email with the note that they will also try to contact Florian ans request him to move the package to  debian-astro.

The important thing is to put all bit's of knowledge as a comment here in this issue.

Do you need help, maven-izing your project? 

The command series to debianize nom-tam-fits.
´``
export DEBFULLNAME="Your Name"
export DEBEMAIL=your@home
export DEBLICENSE="BSD"
sudo apt-get install apt-file
sudo apt-get install devscripts
mkdir debian-fits 
cd debian-fits
wget https://github.com/nom-tam-fits/nom-tam-fits/archive/nom-tam-fits-1.14.2.tar.gz
tar xvzf nom-tam-fits-1.14.2.tar.gz
cd nom-tam-fits-nom-tam-fits-1.14.2/
mh_make
```

**Comment by olebole** [comment]
Hi,

Debian has now the current version of `nom.tam.fits` ([1.15.1]https://packages.debian.org/source/stretch/libfits-java)). So, this issue could be closed.
