### ISSUE TITLE
new standard comment handling

### ISSUE THREAD

**Issue by ritchieGitHub** [nom-tam-fits/nom-tam-fits#9]
because the standard comments are now in the enumerations the comment handling has to be adapted accordingly.

ready for review in the "local" branch

**Comment by TomMcGlynn** [comment]
Showing my lack of experience with GIT and GITHub, I've been unable to see the changes that I'm supposed to be reviewing.  I downloaded a complete version of the local branch...

**Comment by ritchieGitHub** [comment]
Hi,

today I will try to do the fixes and deploy a snapshot, tomorrow i will
send you some pointers where to look.

regards,
Ritchie

Am 2015-04-08 um 21:37 schrieb TomMcGlynn:
> Showing my lack of experience with GIT and GITHub, I've been unable to
> see the changes that I'm supposed to be reviewing. I downloaded a
> complete version of the local branch...
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nom-tam-fits/nom-tam-fits/issues/9#issuecomment-91014152>.
> 


-- 
BSc Richard van Nieuwenhoven
Software Architekt

adesso Austria GmbH
floridotower 26. Stock              T +43 1 2198790-0
Foridsdorfer Hauptstr. 1            F +43 1 2198790-13
A-1210 Wien                         H +43 664 88614710
                                    E richard.vannieuwenhoven@adesso.at
                                    www.adesso.at
-------------------------------------------------------------
         >>> business. people. technology. <<<
-------------------------------------------------------------
adesso Austria GmbH mit Sitz in Wien
Handelsgericht Wien FN231467v

**Comment by ritchieGitHub** [comment]
new api posponed
