### ISSUE TITLE
Add support for BZERO, BSCALE, TZEROn, and TSCALn as defined in the FITS standard

### ISSUE THREAD

**Issue by wcleveland** [nom-tam-fits/nom-tam-fits#95]
The library should provide a new method of retrieving values already transformed and scaled as specified by the FITS standard. This change will not affect current methods of retrieving values to prevent breakage of applications not expecting this behavior.

From the standard: 

BSCALE keyword. This keyword shall be used, along with the BZERO keyword, to linearly scale the array pixel values (i.e., the actual values stored in the FITS file) to transform them into the physical values that they represent using:

physical value = BZERO + BSCALE × array value      (3)

TZEROn keywords. This indexed keyword shall be used, along with the TSCALn keyword, to linearly scale the values in the table field n to transform them into the physical values that they represent using: 

physical value = TZEROn + TSCALn × field value       (7)

It must not be used if the format of field n is A, L, or X. For fields with all other data types, the value field shall contain a floating-point number representing the true physical value corresponding to a value of zero in field n of the FITS file, or, in the case of the complex data types C and M, in the real part of the field, with the imaginary part set to zero. The default value for this keyword is 0.0. Equation 7 is used to compute a true physical value from the quantity in field n. For fields of type P or Q, the values of TSCALn and TZEROn are to be applied to the values in the data array in the heap area, not the values of the array descriptor.

**Comment by wcleveland** [comment]
I'm almost caught up with work and will submit a pull request with this feature later.

**Comment by attipaci** [comment]
I assume the merging of the above pull request has resolved this issue, and so I'll go ahead and close this one...
