### ISSUE TITLE
Outdated documentation in introduction

### ISSUE THREAD

**Issue by MaxNoe** [nom-tam-fits/nom-tam-fits#98]
The main introduction on this website:
http://nom-tam-fits.github.io/nom-tam-fits/intro.html
contains outdated documentation and invalid code.

I wanted to implement a streamed binary table writer, but the example given there is not possible.
E. g. there is not method `Fits.getNullHDU` (anymore?).

The example also contains invalid syntax, row is used before it is declared and the `Object[] data` creation is invalid.

Can you update this example? We would really appreciate the possibility to append rows to a binary table file.

**Comment by ritchieGitHub** [comment]
Thank you for pointing out the error in the documentation, it is very old .... This is an open source project so if you would be willing to correct that specific part (now you found the errors). You could do it as a pull request. The source of the site is located here:

https://github.com/nom-tam-fits/nom-tam-fits/blob/master/src/site/markdown/intro.md

Markdown is a easy to learn. That help would be greatly appreciated.

**Comment by ritchieGitHub** [comment]
for got to close the, corresponding issue ;)
