### ISSUE TITLE
How to modify file in place?

### ISSUE THREAD

**Issue by maxnoe** [nom-tam-fits/nom-tam-fits#99]
Is it still possible to modify a file inplace?

The `Fits` object does not have a method `rewrite` anymore, which is mentioned for this task in the introduction in the docs.

see also #98

**Comment by ritchieGitHub** [comment]
Sorry, I am rather busy at the moment. This Friday I will have time to look into your issues.

**Comment by MaxNoe** [comment]
Thanks!

In the mean time I found that the `Header` now has a `rewrite` method. This seems to work.

**Comment by ritchieGitHub** [comment]
The rewrite method is available on all elements but Fits itself. Because Fits intentionally forgets HDU's depending on the way you work with them, the rewrite would not act act as expected in that case.

**Comment by attipaci** [comment]
Hi I assume this can be closed now. If not, feel free to reopen again. 

Relatedly, I have updated the online documentation, both on the project site and the github README (same). There is a section in them on modifying files in place.
